<!-- ! This file is automatically generated, please don't edit it directly. -->

<svelte:options namespace="svg" />

<script>export let size = 24;
export let color = 'currentColor';
export let strokeWidth = 2;
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-bill">
		<path
			class="oi-box"
			d="M20 6H4C3.44772 6 3 6.44772 3 7V17C3 17.5523 3.44772 18 4 18H20C20.5523 18 21 17.5523 21 17V7C21 6.44772 20.5523 6 20 6Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-miterlimit="10"
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path class="oi-fill" d="M5 10.5V8H7.5L5 10.5Z" fill={color} />
		<path class="oi-fill" d="M19 10.5V8H16.5L19 10.5Z" fill={color} />
		<path class="oi-fill" d="M7.5 16L5 16L5 13.5L7.5 16Z" fill={color} />
		<path class="oi-fill" d="M16.5 16L19 16L19 13.5L16.5 16Z" fill={color} />
		<circle
			class="oi-ellipse"
			cx="12"
			cy="12"
			r="3"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-miterlimit="10"
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
	</g>
</svg>
