<!-- ! This file is automatically generated, please don't edit it directly. -->

<svelte:options namespace="svg" />

<script>export let size = 24;
export let color = 'currentColor';
export let strokeWidth = 2;
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-headphones">
		<path
			class="oi-vector"
			d="M20.0614 16.7896L19.8026 17.7555C19.3737 19.3559 17.7287 20.3057 16.1283 19.8769L15.1624 19.618L16.9741 12.8566L17.9401 13.1154C19.5405 13.5442 20.4902 15.1892 20.0614 16.7896ZM20.0614 16.7896C20.0614 16.7896 21.1667 15.0001 21 12.0001C20.8334 9.00011 18.9 3.00011 12.5 3.00011L11.4585 3.00011C5.05845 3.00011 3.12512 9.00011 2.95845 12.0001C2.79179 15.0001 3.89709 16.7896 3.89709 16.7896M3.89709 16.7896L4.15591 17.7555C4.58473 19.3559 6.22974 20.3057 7.83014 19.8769L8.79607 19.618L6.98433 12.8566L6.01841 13.1154C4.41801 13.5442 3.46826 15.1892 3.89709 16.7896Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-miterlimit="10"
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
	</g>
</svg>
