<!-- ! This file is automatically generated, please don't edit it directly. -->

<svelte:options namespace="svg" />

<script>export let size = 24;
export let color = 'currentColor';
export let strokeWidth = 2;
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-masonry">
		<rect
			class="oi-box"
			x="3"
			y="3"
			width="7"
			height="9"
			rx="1"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<rect
			class="oi-box"
			x="14"
			y="12"
			width="7"
			height="9"
			rx="1"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<rect
			class="oi-box"
			x="3"
			y="16"
			width="7"
			height="5"
			rx="1"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<rect
			class="oi-box"
			x="14"
			y="3"
			width="7"
			height="5"
			rx="1"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
	</g>
</svg>
