<!-- ! This file is automatically generated, please don't edit it directly. -->

<svelte:options namespace="svg" />

<script>export let size = 24;
export let color = 'currentColor';
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-pin-fill">
		<path
			class="oi-fill"
			fill-rule="evenodd"
			clip-rule="evenodd"
			d="M12 14C12.5523 14 13 14.4477 13 15V21C13 21.5523 12.5523 22 12 22C11.4477 22 11 21.5523 11 21V15C11 14.4477 11.4477 14 12 14Z"
			fill={color}
		/>
		<path
			class="oi-fill"
			d="M18.7876 15.055C18.7005 13.8748 18.3471 11.8471 17 10.5L17 3H7L7 10.5C5.65286 11.8471 5.29956 13.8748 5.21246 15.0551C5.17336 15.5848 5.60643 16 6.13759 16H17.8625C18.3936 16 18.8267 15.5848 18.7876 15.055Z"
			fill={color}
		/>
		<path
			class="oi-fill"
			fill-rule="evenodd"
			clip-rule="evenodd"
			d="M6 3C6 2.44772 6.44772 2 7 2H17C17.5523 2 18 2.44772 18 3C18 3.55228 17.5523 4 17 4H7C6.44772 4 6 3.55228 6 3Z"
			fill={color}
		/>
	</g>
</svg>
