<!-- ! This file is automatically generated, please don't edit it directly. -->

<svelte:options namespace="svg" />

<script>export let size = 24;
export let color = 'currentColor';
export let strokeWidth = 2;
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-sigma">
		<path
			class="oi-vector"
			d="M19 3H5.22905C4.78054 3 4.55887 3.54489 4.88 3.858L12.8636 11.642C13.0649 11.8382 13.0649 12.1618 12.8636 12.358L4.88 20.142C4.55887 20.4551 4.78054 21 5.22905 21H19"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
		/>
	</g>
</svg>
