<!-- ! This file is automatically generated, please don't edit it directly. -->

<svelte:options namespace="svg" />

<script>export let size = 24;
export let color = 'currentColor';
export let strokeWidth = 2;
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-sleep">
		<path
			class="oi-vector"
			d="M5 3H11.8376C11.9534 3 12.0216 3.13001 11.9558 3.22532L5.15555 13.0762C5.08975 13.1716 5.15797 13.3016 5.2738 13.3016H12.1114"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
		/>
		<path
			class="oi-vector"
			d="M8.57709 16.4138H11.8898C11.9723 16.4138 12.0199 16.5073 11.9714 16.574L8.69359 21.0811C8.6451 21.1478 8.69273 21.2413 8.77517 21.2413H12.0879"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
		/>
		<path
			class="oi-vector"
			d="M15 9.85596H19.54C19.653 9.85596 19.7183 9.98413 19.6518 10.0755L15.1597 16.2524C15.0932 16.3438 15.1585 16.472 15.2715 16.472H19.8115"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
		/>
	</g>
</svg>
