<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'BarChart',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
		strokeWidth: { type: Number, default: 2 },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-bar-chart">
			<rect
				class="oi-box"
				x="3"
				y="3"
				width="4"
				height="18"
				rx="1"
				:stroke="color"
				:stroke-width="strokeWidth"
			/>
			<rect
				class="oi-box"
				x="10"
				y="8"
				width="4"
				height="13"
				rx="1"
				:stroke="color"
				:stroke-width="strokeWidth"
			/>
			<rect
				class="oi-box"
				x="17"
				y="13"
				width="4"
				height="8"
				rx="1"
				:stroke="color"
				:stroke-width="strokeWidth"
			/>
		</g>
	</svg>
</template>
