<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'BrandNpmFill',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-brand-npm-fill">
			<path
				class="oi-fill"
				d="M22 22H2V2H22V22ZM5.75 5.75V18.25H12V8.25H15.75V18.25H18.25V5.75H5.75Z"
				:fill="color"
			/>
		</g>
	</svg>
</template>
