<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'BudgetAlt',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
		strokeWidth: { type: Number, default: 2 },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-budget-alt">
			<path
				class="oi-fill"
				d="M19.9951 17.1522C20.29 17.6178 20.4638 18.1665 20.4639 18.7684C20.4639 20.5843 18.8941 21.9226 17.1299 21.9227C15.3656 21.9227 13.7959 20.5843 13.7959 18.7684C13.7959 18.1667 13.9689 17.6178 14.2637 17.1522C14.6333 17.7365 15.1945 18.1895 15.8506 18.4481C15.8145 18.553 15.7959 18.6613 15.7959 18.7684C15.7959 19.3321 16.3164 19.9227 17.1299 19.9227C17.9433 19.9226 18.4639 19.332 18.4639 18.7684C18.4638 18.6612 18.4444 18.5531 18.4082 18.4481C19.0645 18.1896 19.6253 17.7365 19.9951 17.1522Z"
				:fill="color"
			/>
			<ellipse
				class="oi-ellipse"
				cx="17.1299"
				cy="15.5372"
				rx="2.42355"
				ry="2.15427"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<path
				class="oi-vector"
				d="M10.1416 8.40451L6.10211 3.92714C10.0973 2.14475 12.8606 3.18448 13.7429 3.92714L10.1416 8.40451Z"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<path
				class="oi-vector"
				d="M4.74438 6.75879C5.42929 7.21879 5.88925 7.78639 7.44511 8.13874C9.59272 8.6251 13.3756 8.13869 14.0508 9.66531"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<path
				class="oi-vector"
				d="M12.1 20.975C11.3465 20.975 8.25448 20.975 6.22285 20.975C4.19121 20.975 3.58548 19.1174 3.53656 18.1885C3.53656 13.2591 7.50176 9.86687 10.1306 8.4043"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
		</g>
	</svg>
</template>
