<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'Burger',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
		strokeWidth: { type: Number, default: 2 },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-burger">
			<path
				class="oi-vector"
				d="M4.74278 7.14305C5.5021 5.24476 7.34064 4 9.38516 4L14.6148 4C16.6594 4 18.4979 5.24475 19.2572 7.14305L19.4514 7.62861C19.7142 8.28547 19.2304 9 18.523 9L5.47703 9C4.76957 9 4.28581 8.28547 4.54856 7.62861L4.74278 7.14305Z"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<path
				class="oi-mini-dot"
				d="M9 6.48999L9 6.49999"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<path
				class="oi-mini-dot"
				d="M12 6.48999L12 6.49999"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<path
				class="oi-mini-dot"
				d="M15 6.48999L15 6.49999"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<path
				class="oi-vector"
				d="M4 15L4.74278 16.857C5.5021 18.7552 7.34064 20 9.38516 20L14.6148 20C16.6594 20 18.4979 18.7552 19.2572 16.857L20 15"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linejoin="round"
			/>
			<path
				class="oi-vector"
				d="M21 16L18.9926 14.7361C18.289 14.2931 17.3847 14.3316 16.7213 14.8328L16.3821 15.0891C15.6687 15.6281 14.6842 15.6281 13.9708 15.0891L13.6317 14.8328C12.9683 14.3316 12.064 14.2931 11.3604 14.7361L10.4186 15.3291C9.76732 15.7391 8.93856 15.7391 8.28731 15.3291L7.2421 14.6709C6.59085 14.2609 5.76209 14.2609 5.11084 14.6709L3 16"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
			/>
			<path
				class="oi-line"
				d="M4 12H20"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
		</g>
	</svg>
</template>
