<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'CalendarEndOfMonth',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
		strokeWidth: { type: Number, default: 2 },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-calendar-end-of-month">
			<path
				class="oi-vector"
				d="M4 6C4 5.44772 4.44772 5 5 5H19C19.5523 5 20 5.44772 20 6V19C20 19.5523 19.5523 20 19 20H5C4.44772 20 4 19.5523 4 19V6Z"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-miterlimit="10"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<path
				class="oi-vector"
				d="M7.87867 10.7532C8.11677 10.5021 8.7734 10 9.73057 10C10.6161 10 11.4029 10.4448 11.5157 11.4418C11.6806 12.8991 9.38884 13.0574 8.39587 13.0574C9.37957 13.0774 11.7389 13.5477 11.508 14.9542C11.3351 16.0072 10.1709 16.2593 9.73057 16.2676C9.25436 16.2766 8.38662 16.0524 7.66702 15.5144"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
			/>
			<path
				class="oi-vector"
				d="M15.9643 16.2679V10.2984C15.9643 10.0816 15.7004 9.975 15.5498 10.1309L14.0357 11.6982"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
			/>
			<path
				class="oi-line"
				d="M9 7L9 3"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<path
				class="oi-line"
				d="M15 7L15 3"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
		</g>
	</svg>
</template>
