<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'CircleBack',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
		strokeWidth: { type: Number, default: 2 },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-circle-back">
			<circle
				class="oi-ellipse"
				cx="12"
				cy="12.0001"
				r="9"
				:stroke="color"
				:stroke-width="strokeWidth"
			/>
			<path
				class="oi-vector"
				d="M10 12L8 10M8 10L10 8M8 10L13 10C14.6569 10 16 11.3431 16 13C16 14.6569 14.6569 16 13 16L12 16"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-miterlimit="10"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
		</g>
	</svg>
</template>
