<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'CircleArrowUpFill',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-circle-arrow-up-fill">
			<path
				class="oi-fill"
				d="M12 2C17.5228 2 22 6.47715 22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12C2 6.47715 6.47715 2 12 2ZM12.707 6.29297C12.3165 5.90246 11.6835 5.90248 11.293 6.29297L7.29297 10.293C6.90244 10.6835 6.90244 11.3165 7.29297 11.707C7.6835 12.0975 8.31652 12.0975 8.70703 11.707L11 9.41406V17C11 17.5523 11.4477 18 12 18C12.5522 18 13 17.5523 13 17V9.41406L15.293 11.707C15.6835 12.0975 16.3165 12.0975 16.707 11.707C17.0975 11.3165 17.0975 10.6835 16.707 10.293L12.707 6.29297Z"
				:fill="color"
			/>
		</g>
	</svg>
</template>
