<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'CircleDivideFill',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-circle-divide-fill">
			<path
				class="oi-fill"
				d="M12 2C17.5228 2 22 6.47715 22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12C2 6.47715 6.47715 2 12 2ZM15.707 8.29297C15.3165 7.90244 14.6835 7.90244 14.293 8.29297L8.29297 14.293C7.90244 14.6835 7.90244 15.3165 8.29297 15.707C8.6835 16.0975 9.31653 16.0975 9.70703 15.707L15.707 9.70703C16.0975 9.31653 16.0975 8.6835 15.707 8.29297ZM14.4883 13.5C13.936 13.5 13.4883 13.9477 13.4883 14.5C13.4884 15.0522 13.9361 15.5 14.4883 15.5H14.5L14.6025 15.4951C15.1065 15.4437 15.4999 15.0175 15.5 14.5C15.5 13.9824 15.1066 13.5563 14.6025 13.5049L14.5 13.5H14.4883ZM9.48828 8.5C8.93604 8.5 8.48835 8.94777 8.48828 9.5C8.48832 10.0522 8.93602 10.5 9.48828 10.5H9.5L9.60254 10.4951C10.1066 10.4438 10.5 10.0176 10.5 9.5C10.4999 8.98239 10.1066 8.55623 9.60254 8.50488L9.5 8.5H9.48828Z"
				:fill="color"
			/>
		</g>
	</svg>
</template>
