<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'ClipboardAddFill',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-clipboard-add-fill">
			<path
				class="oi-fill"
				d="M8.26953 2C8.09906 2.29437 8 2.63536 8 3V5C8 6.10457 8.89543 7 10 7H14C15.1046 7 16 6.10457 16 5V3C16 2.63536 15.9009 2.29437 15.7305 2H18C19.6569 2 21 3.34315 21 5V20C21 21.6569 19.6569 23 18 23H6C4.34315 23 3 21.6569 3 20V5C3 3.34315 4.34315 2 6 2H8.26953ZM12 10.5C11.4477 10.5 11 10.9477 11 11.5V13H9.5C8.94772 13 8.5 13.4477 8.5 14C8.5 14.5523 8.94772 15 9.5 15H11V16.5C11 17.0523 11.4477 17.5 12 17.5C12.5523 17.5 13 17.0523 13 16.5V15H14.5L14.6025 14.9951C15.1067 14.9438 15.5 14.5177 15.5 14C15.5 13.4823 15.1067 13.0562 14.6025 13.0049L14.5 13H13V11.5C13 10.9477 12.5523 10.5 12 10.5ZM14 5H10V3H14V5Z"
				:fill="color"
			/>
		</g>
	</svg>
</template>
