<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'Diamond',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
		strokeWidth: { type: Number, default: 2 },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-diamond">
			<path
				class="oi-vector"
				d="M21 10L17 5H12M21 10L12 20M21 10L16 10M12 20L3 10M12 20L16 10M12 20L8 10M3 10L7 5H12M3 10H8M8 10L12 5M8 10L16 10M12 5L16 10"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-miterlimit="2.16568"
				stroke-linecap="round"
			/>
		</g>
	</svg>
</template>
