<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'Drop',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
		strokeWidth: { type: Number, default: 2 },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-drop">
			<path
				class="oi-vector"
				d="M12 21C8.13399 21 4.99998 17.866 4.99998 14C4.99998 9 12 3 12 3C12 3 19 9 19 14C19 17.866 15.866 21 12 21Z"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-miterlimit="10"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<path
				class="oi-vector"
				d="M8.64488 15C8.98086 16.1289 9.87105 17.0191 10.9999 17.3551"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-miterlimit="10"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
		</g>
	</svg>
</template>
