<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'Flag',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
		strokeWidth: { type: Number, default: 2 },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-flag">
			<path
				class="oi-vector"
				d="M4.00007 4.00005C12.0001 2.00005 12.0001 7.00005 20.0001 5.00005C20.0001 8.00005 20.0001 13 20.0001 16C12.0001 18 12.0001 13 4.00007 15C4.00007 12 3.99992 7.00006 4.00007 4.00005ZM4.00007 4.00005L4 21"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-miterlimit="10"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
		</g>
	</svg>
</template>
