<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'FolderDownloadFill',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-folder-download-fill">
			<path
				class="oi-fill"
				d="M9 4C9.26522 4 9.5195 4.10543 9.70703 4.29297L11.4141 6H20C21.1046 6 22 6.89543 22 8V18C22 19.1046 21.1046 20 20 20H4C2.89543 20 2 19.1046 2 18V6C2 4.89543 2.89543 4 4 4H9ZM12 9.5C11.4477 9.5 11 9.94772 11 10.5V13.0859L10.707 12.793L10.6309 12.7246C10.2381 12.4043 9.65908 12.4269 9.29297 12.793C8.92685 13.1591 8.90426 13.7381 9.22461 14.1309L9.29297 14.207L11.293 16.207C11.4805 16.3946 11.7348 16.5 12 16.5C12.2321 16.5 12.4558 16.4193 12.6338 16.2734L12.707 16.207L14.707 14.207C15.0976 13.8165 15.0976 13.1835 14.707 12.793C14.3165 12.4024 13.6835 12.4024 13.293 12.793L13 13.0859V10.5C13 9.94772 12.5523 9.5 12 9.5Z"
				:fill="color"
			/>
		</g>
	</svg>
</template>
