<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'FolderRemoveFill',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-folder-remove-fill">
			<path
				class="oi-fill"
				d="M9 4C9.26522 4 9.5195 4.10543 9.70703 4.29297L11.4141 6H20C21.1046 6 22 6.89543 22 8V18C22 19.1046 21.1046 20 20 20H4C2.89543 20 2 19.1046 2 18V6C2 4.89543 2.89543 4 4 4H9ZM9.5 12C8.94772 12 8.5 12.4477 8.5 13C8.5 13.5523 8.94772 14 9.5 14H14.5L14.6025 13.9951C15.1067 13.9438 15.5 13.5177 15.5 13C15.5 12.4823 15.1067 12.0562 14.6025 12.0049L14.5 12H9.5Z"
				:fill="color"
			/>
		</g>
	</svg>
</template>
