<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'FolderErrorFill',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-folder-error-fill">
			<path
				class="oi-fill"
				d="M9 4C9.26522 4 9.5195 4.10543 9.70703 4.29297L11.4141 6H20C21.1046 6 22 6.89543 22 8V18C22 19.1046 21.1046 20 20 20H4C2.89543 20 2 19.1046 2 18V6C2 4.89543 2.89543 4 4 4H9ZM14.707 10.293C14.3165 9.90244 13.6835 9.90244 13.293 10.293L12 11.5859L10.707 10.293C10.3165 9.90244 9.68349 9.90244 9.29297 10.293C8.90244 10.6835 8.90244 11.3165 9.29297 11.707L10.5859 13L9.29297 14.293C8.90244 14.6835 8.90244 15.3165 9.29297 15.707C9.68349 16.0976 10.3165 16.0976 10.707 15.707L12 14.4141L13.293 15.707L13.3691 15.7754C13.7619 16.0957 14.3409 16.0731 14.707 15.707C15.0731 15.3409 15.0957 14.7619 14.7754 14.3691L14.707 14.293L13.4141 13L14.707 11.707C15.0976 11.3165 15.0976 10.6835 14.707 10.293Z"
				:fill="color"
			/>
		</g>
	</svg>
</template>
