<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'Football',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
		strokeWidth: { type: Number, default: 2 },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-football">
			<path
				class="oi-vector"
				d="M17.4881 17.4881C13.4569 21.5194 7.86375 21.1959 5.17406 20.7403C4.69569 20.6595 4.25436 20.4317 3.91131 20.0887C3.56826 19.7456 3.34051 19.3043 3.25968 18.8259C2.80406 16.1362 2.4825 10.5412 6.51187 6.51187C10.5412 2.4825 16.1362 2.80406 18.8259 3.25968C19.3043 3.34051 19.7456 3.56826 20.0887 3.91131C20.4317 4.25436 20.6595 4.69569 20.7403 5.17406C21.1959 7.86375 21.5175 13.4587 17.4881 17.4881Z"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<path
				class="oi-line"
				d="M9.75 12L12 14.25"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<path
				class="oi-line"
				d="M12 9.75L14.25 12"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<path
				class="oi-line"
				d="M15 9L9 15"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<path
				class="oi-line"
				d="M13.6359 3.13593L20.8641 10.3641"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<path
				class="oi-line"
				d="M3.13593 13.6359L10.3641 20.8641"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
		</g>
	</svg>
</template>
