<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'GameControllerNes',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
		strokeWidth: { type: Number, default: 2 },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-game-controller-nes">
			<path
				class="oi-line"
				d="M6.59998 11.9999H10.2"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<path
				class="oi-line"
				d="M8.40002 10.2001V13.8001"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<path
				class="oi-mini-dot"
				d="M14.7 12.8998H14.709"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<path
				class="oi-mini-dot"
				d="M17.4 11.1H17.409"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<path
				class="oi-box"
				d="M19.2 6.59998H4.8C3.80589 6.59998 3 7.40586 3 8.39998V15.6C3 16.5941 3.80589 17.4 4.8 17.4H19.2C20.1941 17.4 21 16.5941 21 15.6V8.39998C21 7.40586 20.1941 6.59998 19.2 6.59998Z"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
		</g>
	</svg>
</template>
