<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'Heartrate',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
		strokeWidth: { type: Number, default: 2 },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-heartrate">
			<path
				class="oi-vector"
				d="M21.4999 12H17.9999L14.9999 21L8.99994 3L5.99994 12H2.49994"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
		</g>
	</svg>
</template>
