<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'KanbanFill',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-kanban-fill">
			<path
				class="oi-fill"
				d="M19 2C20.6569 2 22 3.34315 22 5V19C22 20.6569 20.6569 22 19 22H5C3.34315 22 2 20.6569 2 19V5C2 3.34315 3.34315 2 5 2H19ZM7 6C6.44772 6 6 6.44772 6 7V16C6 16.5523 6.44772 17 7 17H10C10.5523 17 11 16.5523 11 16V7C11 6.44772 10.5523 6 10 6H7ZM14.001 6C13.4487 6 13.001 6.44772 13.001 7V12C13.001 12.5523 13.4487 13 14.001 13H17.001C17.553 12.9997 18.001 12.5521 18.001 12V7C18.001 6.44788 17.553 6.00026 17.001 6H14.001Z"
				:fill="color"
			/>
		</g>
	</svg>
</template>
