<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'MasonryAlt',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
		strokeWidth: { type: Number, default: 2 },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-masonry-alt">
			<rect
				class="oi-box"
				x="21"
				y="3"
				width="7"
				height="9"
				rx="1"
				transform="rotate(90 21 3)"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<rect
				class="oi-box"
				x="12"
				y="14"
				width="7"
				height="9"
				rx="1"
				transform="rotate(90 12 14)"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<rect
				class="oi-box"
				x="8"
				y="3"
				width="7"
				height="5"
				rx="1"
				transform="rotate(90 8 3)"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<rect
				class="oi-box"
				x="21"
				y="14"
				width="7"
				height="5"
				rx="1"
				transform="rotate(90 21 14)"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
		</g>
	</svg>
</template>
