<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'OfficeChair',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
		strokeWidth: { type: Number, default: 2 },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-office-chair">
			<path
				class="oi-vector"
				d="M6.75111 21.7499C6.75111 21.1531 6.98816 20.5808 7.41012 20.1589C7.83207 19.7369 8.40437 19.4999 9.00111 19.4999H15.0011C15.5978 19.4999 16.1701 19.7369 16.5921 20.1589C17.0141 20.5808 17.2511 21.1531 17.2511 21.7499"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<path
				class="oi-line"
				d="M12.0011 15.7499V21.7499"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<path
				class="oi-vector"
				d="M1.50111 11.9999H3.75111C3.75111 12.9944 4.14619 13.9483 4.84946 14.6515C5.55272 15.3548 6.50654 15.7499 7.50111 15.7499H16.5011C17.4957 15.7499 18.4495 15.3548 19.1528 14.6515C19.856 13.9483 20.2511 12.9944 20.2511 11.9999H22.5011"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<path
				class="oi-vector"
				d="M8.78736 2.24988C8.6068 2.24987 8.4323 2.31501 8.2959 2.43332C8.1595 2.55164 8.07037 2.71519 8.04486 2.89394L6.75861 11.8939C6.74343 12.0003 6.75129 12.1087 6.78164 12.2118C6.812 12.3148 6.86414 12.4102 6.93455 12.4913C7.00496 12.5725 7.09198 12.6376 7.18973 12.6822C7.28747 12.7268 7.39367 12.7499 7.50111 12.7499H16.5011C16.6086 12.7499 16.7147 12.7268 16.8125 12.6822C16.9102 12.6376 16.9973 12.5725 17.0677 12.4913C17.1381 12.4102 17.1902 12.3148 17.2206 12.2118C17.2509 12.1087 17.2588 12.0003 17.2436 11.8939L15.9574 2.89394C15.9319 2.71519 15.8427 2.55164 15.7063 2.43332C15.5699 2.31501 15.3954 2.24987 15.2149 2.24988H8.78736Z"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
		</g>
	</svg>
</template>
