<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'PhoneFill',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-phone-fill">
			<path
				class="oi-fill"
				d="M16 1.5C17.1046 1.5 18 2.39543 18 3.5V20.5C18 21.6046 17.1046 22.5 16 22.5H8C6.89543 22.5 6 21.6046 6 20.5V3.5C6 2.39543 6.89543 1.5 8 1.5H16ZM12 17C11.4477 17 11 17.4477 11 18C11 18.5523 11.4477 19 12 19H12.0117L12.1143 18.9951C12.6185 18.9439 13.0117 18.5178 13.0117 18C13.0117 17.4822 12.6185 17.0561 12.1143 17.0049L12.0117 17H12Z"
				:fill="color"
			/>
		</g>
	</svg>
</template>
