<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'PullRequest',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
		strokeWidth: { type: Number, default: 2 },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-pull-request">
			<circle
				class="oi-ellipse"
				cx="7.03174"
				cy="18.5"
				r="1.5"
				:stroke="color"
				:stroke-width="strokeWidth"
			/>
			<circle
				class="oi-ellipse"
				cx="17.0317"
				cy="18.5"
				r="1.5"
				:stroke="color"
				:stroke-width="strokeWidth"
			/>
			<circle
				class="oi-ellipse"
				cx="7.03174"
				cy="5.5"
				r="1.5"
				:stroke="color"
				:stroke-width="strokeWidth"
			/>
			<path
				class="oi-line"
				d="M7.03174 6.5L7.03174 17"
				:stroke="color"
				:stroke-width="strokeWidth"
			/>
			<path
				class="oi-vector"
				d="M16.9317 17V9C16.9317 7 16.0317 6 13.9317 6H12.5317"
				:stroke="color"
				:stroke-width="strokeWidth"
			/>
			<path
				class="oi-fill"
				d="M13.5317 3L10.5317 5.66667L13.5317 9V3Z"
				:fill="color"
			/>
		</g>
	</svg>
</template>
