<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'RadioOn',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
		strokeWidth: { type: Number, default: 2 },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-radio-on">
			<circle class="oi-fill" cx="12" cy="12" r="3" :fill="color" />
			<circle
				class="oi-ellipse"
				cx="12"
				cy="12"
				r="6"
				:stroke="color"
				:stroke-width="strokeWidth"
			/>
		</g>
	</svg>
</template>
