<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'ReorderAlt',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
		strokeWidth: { type: Number, default: 2 },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-reorder-alt">
			<path
				class="oi-dot"
				d="M7.99402 6H8.00602"
				:stroke="color"
				:stroke-width="strokeWidth * 2"
				stroke-linecap="round"
			/>
			<path
				class="oi-dot"
				d="M15.994 6H16.006"
				:stroke="color"
				:stroke-width="strokeWidth * 2"
				stroke-linecap="round"
			/>
			<path
				class="oi-dot"
				d="M7.99402 12H8.00602"
				:stroke="color"
				:stroke-width="strokeWidth * 2"
				stroke-linecap="round"
			/>
			<path
				class="oi-dot"
				d="M15.994 12H16.006"
				:stroke="color"
				:stroke-width="strokeWidth * 2"
				stroke-linecap="round"
			/>
			<path
				class="oi-dot"
				d="M7.99402 18H8.00602"
				:stroke="color"
				:stroke-width="strokeWidth * 2"
				stroke-linecap="round"
			/>
			<path
				class="oi-dot"
				d="M15.994 18H16.006"
				:stroke="color"
				:stroke-width="strokeWidth * 2"
				stroke-linecap="round"
			/>
		</g>
	</svg>
</template>
