<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'Shapes',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
		strokeWidth: { type: Number, default: 2 },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-shapes">
			<circle
				class="oi-ellipse"
				cx="17"
				cy="17"
				r="3.5"
				:stroke="color"
				:stroke-width="strokeWidth"
			/>
			<rect
				class="oi-box"
				x="4"
				y="14"
				width="6"
				height="6"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linejoin="round"
			/>
			<path
				class="oi-triangle"
				d="M12 4L15.5 10H8.5L12 4Z"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linejoin="round"
			/>
		</g>
	</svg>
</template>
