<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'Slider',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
		strokeWidth: { type: Number, default: 2 },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-slider">
			<path
				class="oi-line"
				d="M18.5 12H21.25"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<path
				class="oi-line"
				d="M3 12H10"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<path
				class="oi-box"
				d="M14.75 7H13.75C13.1977 7 12.75 7.44772 12.75 8V15.75C12.75 16.3023 13.1977 16.75 13.75 16.75H14.75C15.3023 16.75 15.75 16.3023 15.75 15.75V8C15.75 7.44772 15.3023 7 14.75 7Z"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-miterlimit="10"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
		</g>
	</svg>
</template>
