<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'Snap',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
		strokeWidth: { type: Number, default: 2 },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-snap">
			<path
				class="oi-vector"
				d="M3 5V13C3 17.9705 7.0295 22 12 22C16.9705 22 21 17.9705 21 13V5M3 5V2H7V5M3 5H7M21 5V2H17V5M21 5H17M7 5V13C7 15.7615 9.2385 18 12 18C14.7615 18 17 15.7615 17 13V5"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
		</g>
	</svg>
</template>
