<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'TabletFill',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-tablet-fill">
			<path
				class="oi-fill"
				d="M18 2C19.1046 2 20 2.89543 20 4V20C20 21.1046 19.1046 22 18 22H6C4.89543 22 4 21.1046 4 20V4C4 2.89543 4.89543 2 6 2H18ZM12 16.5C11.1716 16.5 10.5 17.1716 10.5 18C10.5 18.8284 11.1716 19.5 12 19.5H12.0117C12.8401 19.5 13.5117 18.8284 13.5117 18C13.5117 17.1716 12.8401 16.5 12.0117 16.5H12Z"
				:fill="color"
			/>
		</g>
	</svg>
</template>
