<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'TemperatureFill',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-temperature-fill">
			<path
				class="oi-fill"
				d="M12 1C14.2091 1 16 2.79086 16 5V5.01465L15.9453 12.4834C17.2008 13.5811 18 15.1958 18 17C18 20.3137 15.3137 23 12 23C8.68629 23 6 20.3137 6 17C6 15.1961 6.79858 13.5811 8.05371 12.4834L8 5.00684V5C8 2.79086 9.79086 1 12 1ZM12 15.5C11.1716 15.5 10.5 16.1716 10.5 17C10.5 17.8284 11.1716 18.5 12 18.5H12.0117C12.8401 18.5 13.5117 17.8284 13.5117 17C13.5117 16.1716 12.8401 15.5 12.0117 15.5H12ZM19 10C19.5523 10 20 10.4477 20 11C20 11.5523 19.5523 12 19 12H17C16.4477 12 16 11.5523 16 11C16 10.4477 16.4477 10 17 10H19ZM19 7C19.5523 7 20 7.44772 20 8C20 8.55228 19.5523 9 19 9H17C16.4477 9 16 8.55228 16 8C16 7.44772 16.4477 7 17 7H19ZM19 4C19.5523 4 20 4.44772 20 5C20 5.55228 19.5523 6 19 6H17C16.4477 6 16 5.55228 16 5C16 4.44772 16.4477 4 17 4H19Z"
				:fill="color"
			/>
		</g>
	</svg>
</template>
