<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'Transfer',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
		strokeWidth: { type: Number, default: 2 },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-transfer">
			<path
				class="oi-vector"
				d="M2.39996 15L13.2 15M2.39996 15L6.59996 19.2M2.39996 15L6.59996 10.8"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
			/>
			<path
				class="oi-vector"
				d="M21.6 9.00005L10.8 9.00005M21.6 9.00005L17.4 4.80005M21.6 9.00005L17.4 13.2"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
			/>
		</g>
	</svg>
</template>
