<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'Truck',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
		strokeWidth: { type: Number, default: 2 },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-truck">
			<path
				class="oi-vector"
				d="M14 16V11H21V16H18"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-miterlimit="10"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<path
				class="oi-vector"
				d="M5 16H3V5C3 4.44772 3.44772 4 4 4H14V16H9"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-miterlimit="10"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<path
				class="oi-vector"
				d="M21 11L17.3002 6.3753C17.1105 6.13809 16.8232 6 16.5194 6H14V11H21Z"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-miterlimit="10"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<circle
				class="oi-ellipse"
				cx="7"
				cy="16"
				r="2"
				:stroke="color"
				:stroke-width="strokeWidth"
			/>
			<circle
				class="oi-ellipse"
				cx="16"
				cy="16"
				r="2"
				:stroke="color"
				:stroke-width="strokeWidth"
			/>
		</g>
	</svg>
</template>
