<script>
// ! This file is automatically generated, please don't edit it directly.
export default {
	name: 'Volume1',
	props: {
		size: { type: Number, default: 24 },
		color: { type: String, default: 'currentColor' },
		strokeWidth: { type: Number, default: 2 },
	},
};
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
		class="obra-icon"
	>
		<g class="oi-volume-1">
			<path
				class="oi-vector"
				d="M10.9999 5L5.99988 9H1.99988V15H5.99988L10.9999 19V5Z"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
			<path
				class="oi-vector"
				d="M19.0699 4.93005C20.9446 6.80533 21.9978 9.34841 21.9978 12.0001C21.9978 14.6517 20.9446 17.1948 19.0699 19.0701M15.5399 8.46005C16.4773 9.39769 17.0038 10.6692 17.0038 11.9951C17.0038 13.3209 16.4773 14.5924 15.5399 15.5301"
				:stroke="color"
				:stroke-width="strokeWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
		</g>
	</svg>
</template>
