<!-- ! This file is automatically generated, please don't edit it directly. -->

<script lang="ts">
	export let size = 24;
	export let color = 'currentColor';
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-bank-card-fill">
		<path
			class="oi-fill"
			d="M22 18C22 19.1046 21.1046 20 20 20H4C2.89543 20 2 19.1046 2 18V10.6006H22V18ZM7 13.001C6.44772 13.001 6 13.4487 6 14.001C6.00053 14.5528 6.44804 15.001 7 15.001H9C9.55196 15.001 9.99947 14.5528 10 14.001C10 13.4487 9.55228 13.001 9 13.001H7ZM20 4C21.1046 4 22 4.89543 22 6V8.60059H2V6C2 4.89543 2.89543 4 4 4H20Z"
			fill={color}
		/>
	</g>
</svg>
