<!-- ! This file is automatically generated, please don't edit it directly. -->

<svelte:options namespace="svg" />

<script lang="ts">
  export let size = 24
  export let color = 'currentColor'
  export let strokeWidth = 2
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-basketball">
		<path
			class="oi-vector"
			d="M9 3.5C11 5.66667 15.3853 12.1093 16.5853 19.7093"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M6.60021 19.2179C7.76688 16.7179 12.1479 12.1935 20.9479 12.9935"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M3.07773 10.3859C6.07773 11.2192 13.3251 11.5831 18.5251 5.98309"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<circle
			class="oi-ellipse"
			cx="12"
			cy="12"
			r="9"
			stroke={color}
			stroke-width={strokeWidth}
		/>
	</g>
</svg>
