<!-- ! This file is automatically generated, please don't edit it directly. -->

<script lang="ts">
	export let size = 24;
	export let color = 'currentColor';
	export let strokeWidth = 2;
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-bed">
		<path
			class="oi-line"
			d="M19.5 9H5"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-line"
			d="M19.5 13H5"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-box"
			d="M19.2 3.5H4.8C4.35817 3.5 4 3.83579 4 4.25V20.75C4 21.1642 4.35817 21.5 4.8 21.5H19.2C19.6418 21.5 20 21.1642 20 20.75V4.25C20 3.83579 19.6418 3.5 19.2 3.5Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M7 9V6.5C7 6.22386 7.22386 6 7.5 6H10C10.2761 6 10.5 6.22386 10.5 6.5V9"
			stroke={color}
			stroke-width="1.5"
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M13.5 9V6.5C13.5 6.22386 13.7239 6 14 6H16.5C16.7761 6 17 6.22386 17 6.5V9"
			stroke={color}
			stroke-width="1.5"
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
	</g>
</svg>
