<!-- ! This file is automatically generated, please don't edit it directly. -->

<script lang="ts">
	export let size = 24;
	export let color = 'currentColor';
	export let strokeWidth = 2;
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-bone">
		<path
			class="oi-vector"
			d="M13.8789 4.7074C15.0505 3.53583 16.9495 3.53583 18.1211 4.7074C18.5077 5.09397 18.764 5.56033 18.8955 6.0531C19.3887 6.18442 19.8553 6.44167 20.2422 6.82849C21.4138 8.00006 21.4138 9.89911 20.2422 11.0707C19.3185 11.9943 17.9442 12.1874 16.8291 11.6547L11.6338 16.85C12.1665 17.9651 11.9735 19.3394 11.0498 20.2631C9.87823 21.4346 7.97919 21.4346 6.80762 20.2631C6.4208 19.8762 6.16355 19.4096 6.03223 18.9164C5.53945 18.7849 5.07309 18.5285 4.68652 18.142C3.51495 16.9704 3.51495 15.0714 4.68652 13.8998C5.60978 12.9765 6.98375 12.7829 8.09863 13.3148L13.2939 8.11951C12.7621 7.00463 12.9557 5.63065 13.8789 4.7074Z"
			stroke={color}
			stroke-width={strokeWidth}
		/>
	</g>
</svg>
