<!-- ! This file is automatically generated, please don't edit it directly. -->

<script lang="ts">
	export let size = 24;
	export let color = 'currentColor';
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g
		class="oi-brand-dropbox-fill[dropbox]"
		clip-path="url(#clip0_2603_14077)"
	>
		<path
			class="oi-fill"
			d="M5.92343 2.39368L-0.0762939 6.20922L5.92343 10.0248L11.9241 6.20922L17.9239 10.0248L23.9236 6.20922L17.9239 2.39368L11.9241 6.20922L5.92343 2.39368Z"
			fill={color}
		/>
		<path
			class="oi-fill"
			d="M5.92343 17.6562L-0.0762939 13.8406L5.92343 10.025L11.9241 13.8406L5.92343 17.6562Z"
			fill={color}
		/>
		<path
			class="oi-fill"
			d="M11.9242 13.8406L17.924 10.025L23.9237 13.8406L17.924 17.6562L11.9242 13.8406Z"
			fill={color}
		/>
		<path
			class="oi-fill"
			d="M11.9242 22.743L5.92346 18.9275L11.9242 15.1119L17.9239 18.9275L11.9242 22.743Z"
			fill={color}
		/>
	</g>
	<defs>
		<clipPath class="clip0_2603_14077">
			<rect width={size} height={size} fill="white" />
		</clipPath>
	</defs>
</svg>
