<!-- ! This file is automatically generated, please don't edit it directly. -->

<script lang="ts">
	export let size = 24;
	export let color = 'currentColor';
	export let strokeWidth = null;
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-brand-dropbox-fill" clip-path="url(#clip0_794_40793)">
		<path
			class="oi-fill"
			d="M5.92342 2.39368L-0.0763073 6.20922L5.92342 10.0248L11.9241 6.20922L17.9239 10.0248L23.9236 6.20922L17.9239 2.39368L11.9241 6.20922L5.92342 2.39368Z"
			fill={color}
		/>
		<path
			class="oi-fill"
			d="M5.92342 17.6562L-0.0763073 13.8406L5.92342 10.025L11.9241 13.8406L5.92342 17.6562Z"
			fill={color}
		/>
		<path
			class="oi-fill"
			d="M11.9242 13.8406L17.924 10.025L23.9236 13.8406L17.924 17.6562L11.9242 13.8406Z"
			fill={color}
		/>
		<path
			class="oi-fill"
			d="M11.9242 22.743L5.92345 18.9275L11.9242 15.1119L17.9239 18.9275L11.9242 22.743Z"
			fill={color}
		/>
	</g>
	<defs>
		<clipPath class="clip0_794_40793">
			<rect width={size} height={size} fill="white" />
		</clipPath>
	</defs>
</svg>
