<!-- ! This file is automatically generated, please don't edit it directly. -->

<script lang="ts">
	export let size = 24;
	export let color = 'currentColor';
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-brand-framer-fill">
		<path
			class="oi-fill"
			d="M5.33334 2H18.6667V8.66667H12L5.33334 2ZM5.33334 8.66667H12L18.6667 15.3333H5.33334V8.66667ZM5.33334 15.3333H12V22L5.33334 15.3333Z"
			fill={color}
		/>
	</g>
</svg>
