<!-- ! This file is automatically generated, please don't edit it directly. -->

<script lang="ts">
	export let size = 24;
	export let color = 'currentColor';
	export let strokeWidth = 2;
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-dark-mode">
		<path
			class="oi-fill"
			d="M12 1C12.5523 1 13 1.44772 13 2V8C13 7.44772 12.5523 7 12 7C9.23858 7 7 9.23858 7 12C7 14.7614 9.23858 17 12 17C12.5523 17 13 16.5523 13 16V22C13 22.5523 12.5523 23 12 23C5.92487 23 1 18.0751 1 12C1 5.92487 5.92487 1 12 1Z"
			fill={color}
		/>
		<path
			class="oi-fill"
			d="M16 12C16 14.2091 14.2091 16 12 16V8C14.2091 8 16 9.79086 16 12Z"
			fill={color}
		/>
		<circle
			class="oi-ellipse"
			cx="12"
			cy="12"
			r="10"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
	</g>
</svg>
