<!-- ! This file is automatically generated, please don't edit it directly. -->

<script lang="ts">
	export let size = 24;
	export let color = 'currentColor';
	export let strokeWidth = 2;
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-diamond-cards">
		<path
			class="oi-vector"
			d="M11.4722 2.46864L2.4679 11.473C2.17684 11.764 2.17684 12.236 2.4679 12.527L11.4722 21.5314C11.7633 21.8224 12.2352 21.8224 12.5263 21.5314L21.5306 12.527C21.8217 12.236 21.8217 11.764 21.5306 11.473L12.5263 2.46864C12.2352 2.17758 11.7633 2.17758 11.4722 2.46864Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
	</g>
</svg>
