<!-- ! This file is automatically generated, please don't edit it directly. -->

<svelte:options namespace="svg" />

<script lang="ts">
  export let size = 24
  export let color = 'currentColor'
  export let strokeWidth = 2
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-divorce">
		<path
			class="oi-vector"
			d="M3.96209 5.13087C6.04489 3.08968 9.42177 3.08968 11.5046 5.13087L12 5.6164L12.4954 5.13087C14.5782 3.08968 17.9551 3.08968 20.0379 5.13087C22.1207 7.17205 22.1207 10.4815 20.0379 12.5227L12 20.4L3.96209 12.5227C1.87929 10.4815 1.87929 7.17205 3.96209 5.13087Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-miterlimit="10"
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M11.5 5L12.7639 7.00742C13.2069 7.71102 13.1684 8.61532 12.6672 9.27871L12.4109 9.61786C11.8719 10.3313 11.8719 11.3158 12.4109 12.0292L12.6672 12.3683C13.1684 13.0317 13.2069 13.936 12.7639 14.6396L11.5 16.6471"
			stroke={color}
			stroke-width={strokeWidth}
		/>
	</g>
</svg>
