<!-- ! This file is automatically generated, please don't edit it directly. -->

<script lang="ts">
	export let size = 24;
	export let color = 'currentColor';
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-email-fill">
		<path
			class="oi-fill"
			d="M20 4C21.1046 4 22 4.89543 22 6V18C22 19.1046 21.1046 20 20 20H4C2.89543 20 2 19.1046 2 18V6C2 4.89543 2.89543 4 4 4H20ZM20.7529 5.3418C20.3893 4.92628 19.7574 4.88371 19.3418 5.24707L12 11.6709L4.6582 5.24707C4.24256 4.88371 3.61065 4.92628 3.24707 5.3418C2.88371 5.75744 2.92628 6.38935 3.3418 6.75293L11.3418 13.7529C11.7187 14.0824 12.2813 14.0824 12.6582 13.7529L20.6582 6.75293C21.0737 6.38935 21.1163 5.75744 20.7529 5.3418Z"
			fill={color}
		/>
	</g>
</svg>
