<!-- ! This file is automatically generated, please don't edit it directly. -->

<script lang="ts">
	export let size = 24;
	export let color = 'currentColor';
	export let strokeWidth = 2;
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-fishing">
		<path
			class="oi-vector"
			d="M10 15L7 12V16.5C7 18.9853 9.01472 21 11.5 21C13.9853 21 16 18.9853 16 16.5V11M16 7V3"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<circle
			class="oi-ellipse"
			cx="16"
			cy="9"
			r="2"
			stroke={color}
			stroke-width={strokeWidth}
		/>
	</g>
</svg>
