<!-- ! This file is automatically generated, please don't edit it directly. -->

<script lang="ts">
	export let size = 24;
	export let color = 'currentColor';
	export let strokeWidth = 2;
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-globe-hemisphere-east">
		<path
			class="oi-ellipse"
			d="M12 21C16.9706 21 21 16.9706 21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M17.2894 19.2825L16.4119 18.4041C16.3179 18.3097 16.2004 18.2421 16.0716 18.2081L14.0625 17.6803C13.8841 17.6334 13.7292 17.5223 13.6275 17.3684C13.5258 17.2145 13.4844 17.0285 13.5113 16.8459L13.7344 15.3272C13.7533 15.199 13.8052 15.0779 13.8849 14.9757C13.9646 14.8735 14.0694 14.7937 14.1891 14.7441L17.0438 13.5572C17.1757 13.5024 17.3205 13.4865 17.4612 13.5113C17.6018 13.536 17.7325 13.6004 17.8378 13.6969L20.1563 15.8166"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M4.73346 17.3109L5.66346 16.6997C5.76646 16.6316 5.85106 16.5392 5.90978 16.4306C5.96849 16.322 5.99949 16.2006 6.00002 16.0772L6.01971 12.6806C6.02073 12.5334 6.06471 12.3897 6.14627 12.2672L8.1094 9.33281C8.16569 9.24925 8.23825 9.17789 8.32274 9.12299C8.40723 9.06808 8.50191 9.03077 8.60114 9.01327C8.70036 8.99577 8.8021 8.99844 8.90027 9.02113C8.99844 9.04382 9.09103 9.08605 9.17252 9.14531L11.0297 10.3641C11.1861 10.4767 11.3796 10.5253 11.5706 10.5L14.52 10.1006C14.7021 10.0762 14.8689 9.9858 14.9888 9.84656L17.0681 7.425C17.185 7.28941 17.2495 7.1165 17.25 6.9375V4.6875"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
	</g>
</svg>
