<!-- ! This file is automatically generated, please don't edit it directly. -->

<script lang="ts">
	export let size = 24;
	export let color = 'currentColor';
	export let strokeWidth = 2;
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-globe-hemisphere-west">
		<path
			class="oi-ellipse"
			d="M12 21C16.9706 21 21 16.9706 21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M7.11377 11.5556L8.36252 9.37501C8.42844 9.26083 8.52329 9.16605 8.63752 9.10021C8.75174 9.03438 8.8813 8.99982 9.01314 9.00001H10.5797C10.7064 9.00022 10.831 8.96794 10.9416 8.90626L12.0938 8.27251C12.1445 8.24524 12.1914 8.21152 12.2335 8.1722L14.7572 5.89126C14.8828 5.77705 14.9659 5.62363 14.993 5.45606C15.02 5.2885 14.9895 5.1167 14.9063 4.96876L13.9219 3.20532"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M6.35437 4.9903L5.25 7.60123C5.1754 7.77799 5.17137 7.9766 5.23875 8.15623L6.31687 11.0315C6.36117 11.149 6.43425 11.2535 6.52942 11.3354C6.62458 11.4173 6.73879 11.474 6.86156 11.5003L8.87062 11.9325C8.98205 11.9564 9.08657 12.0054 9.17624 12.0757C9.26591 12.146 9.33837 12.2359 9.38812 12.3384L9.74437 13.0762C9.80582 13.203 9.90173 13.3099 10.0211 13.3846C10.1405 13.4594 10.2785 13.4991 10.4194 13.499H11.7131"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M19.9772 16.17L15.0666 13.1493C14.9773 13.0949 14.8777 13.0595 14.7741 13.0453L12.6347 12.7565C12.474 12.7348 12.3106 12.7657 12.169 12.8446C12.0273 12.9235 11.9151 13.0463 11.8491 13.1943L10.5647 16.0762C10.505 16.2103 10.486 16.359 10.51 16.5038C10.534 16.6486 10.5999 16.7832 10.6997 16.8909L12.5503 18.7968C12.6305 18.8831 12.6893 18.987 12.7219 19.1002C12.7545 19.2134 12.7599 19.3327 12.7378 19.4484L12.4406 20.9897"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
	</g>
</svg>
