<!-- ! This file is automatically generated, please don't edit it directly. -->

<script lang="ts">
	export let size = 24;
	export let color = 'currentColor';
	export let strokeWidth = 2;
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-growing-leaves">
		<path
			class="oi-line"
			d="M11.6935 12.3337V18.1835"
			stroke={color}
			stroke-width="1.5"
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-fill"
			fill-rule="evenodd"
			clip-rule="evenodd"
			d="M16.043 11.1024C17.2216 10.2799 18.2038 8.63387 17.8557 5.3475C16.3448 5.29473 14.521 5.56306 13.2553 6.43232C12.7606 6.77207 12.353 7.20135 12.0738 7.74664C11.857 7.20874 11.5459 6.75489 11.1678 6.37412C11.5167 5.90689 11.9388 5.51679 12.4061 5.19585C14.2636 3.92017 16.8395 3.72525 18.5933 3.89275C18.9371 3.92559 19.2141 4.18906 19.2641 4.53086C19.8557 8.57756 18.7632 11.0332 16.9014 12.3325C15.1139 13.58 12.8264 13.6052 11.3021 13.2902C11.0412 13.2363 10.8284 13.048 10.7432 12.7956C10.7325 12.7638 10.7219 12.7321 10.7115 12.7005C11.1256 12.6805 11.5176 12.6286 11.8701 12.5557C12.1559 11.7092 12.3208 10.9475 12.3839 10.2628C13.2714 9.33035 14.1493 8.58025 14.6224 8.21664C14.9508 7.96423 15.4216 8.02585 15.6741 8.35427C15.9265 8.68269 15.8649 9.15355 15.5364 9.40596C14.9954 9.82178 13.8608 10.8071 12.8704 11.9589C13.9383 11.9768 15.112 11.7521 16.043 11.1024Z"
			fill={color}
		/>
		<path
			class="oi-vector"
			d="M16.1071 19.4086C15.0183 18.6562 13.4443 18.1835 11.6936 18.1835C9.94296 18.1835 8.3689 18.6562 7.28017 19.4086"
			stroke={color}
			stroke-width="1.5"
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M11.87 12.5558C14.2675 5.45369 8.15691 4.319 4.80191 4.63943C3.67103 12.3748 9.04279 13.1401 11.87 12.5558ZM11.87 12.5558C10.7197 10.9053 8.97367 9.37182 8.24447 8.81138"
			stroke={color}
			stroke-width="1.5"
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
	</g>
</svg>
