<!-- ! This file is automatically generated, please don't edit it directly. -->

<script lang="ts">
	export let size = 24;
	export let color = 'currentColor';
	export let strokeWidth = 2;
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-options-vertical-encircled">
		<path
			class="oi-medium-dot"
			d="M12.0118 16.5057L11.9998 16.5057"
			stroke={color}
			stroke-width={strokeWidth * 1.5}
			stroke-linecap="round"
		/>
		<path
			class="oi-medium-dot"
			d="M12.0118 11.7499L11.9998 11.7499"
			stroke={color}
			stroke-width={strokeWidth * 1.5}
			stroke-linecap="round"
		/>
		<path
			class="oi-medium-dot"
			d="M12.0118 7.00574L11.9998 7.00574"
			stroke={color}
			stroke-width={strokeWidth * 1.5}
			stroke-linecap="round"
		/>
		<path
			class="oi-ellipse"
			d="M12 21C16.9706 21 21 16.9706 21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-miterlimit="10"
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
	</g>
</svg>
