<!-- ! This file is automatically generated, please don't edit it directly. -->

<script lang="ts">
	export let size = 24;
	export let color = 'currentColor';
	export let strokeWidth = 2;
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-paint-bucket">
		<path
			class="oi-vector"
			d="M11 6L19 13L12.3184 20.5168C11.5886 21.3378 10.3332 21.4166 9.50656 20.6932L4.51696 16.3273C3.68109 15.596 3.60126 14.3236 4.33915 13.4935L11 6Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M11 13V5C11 3.89543 10.1046 3 9 3V3C7.89543 3 7 3.89543 7 5V10"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-medium-dot"
			d="M11 13H11.012"
			stroke={color}
			stroke-width={strokeWidth * 1.5}
			stroke-linecap="round"
		/>
		<path
			class="oi-fill"
			d="M21.5 17.5C21.5 18.3284 20.8284 19 20 19C19.1716 19 18.5 18.3284 18.5 17.5C18.5 16.6716 20 13 20 13C20 13 21.5 16.6716 21.5 17.5Z"
			fill={color}
		/>
	</g>
</svg>
