<!-- ! This file is automatically generated, please don't edit it directly. -->

<script lang="ts">
	export let size = 24;
	export let color = 'currentColor';
	export let strokeWidth = 2;
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-potted-plant">
		<path
			class="oi-vector"
			d="M13.5263 10.4738C11.175 6.55407 14.31 2.63532 20.9728 3.0272C21.3647 9.69001 17.4459 12.825 13.5263 10.4738Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M9.1875 10.6875C10.8975 7.83657 8.6175 4.98657 3.77156 5.27157C3.48468 10.1156 6.33468 12.3956 9.1875 10.6875Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M5.25 14.25H18.75"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M17.25 14.25L15.8803 20.4131C15.8432 20.5796 15.7504 20.7285 15.6173 20.8352C15.4842 20.9419 15.3187 21 15.1481 21H8.85187C8.68128 21 8.51577 20.9419 8.38266 20.8352C8.24955 20.7285 8.15679 20.5796 8.11969 20.4131L6.75 14.25"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-line"
			d="M13.5262 10.4738L9.75 14.25"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-line"
			d="M9.18562 10.6856L11.25 12.75"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
	</g>
</svg>
