<!-- ! This file is automatically generated, please don't edit it directly. -->

<svelte:options namespace="svg" />

<script lang="ts">
  export let size = 24
  export let color = 'currentColor'
  export let strokeWidth = 2
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-pound">
		<path
			class="oi-vector"
			d="M15.5676 5.44173C13.5482 3.40844 10.0646 3.59276 8.27671 5.86867C7.47599 6.88793 7.11525 8.164 7.29556 9.4411L8.12015 15.2523C8.35863 16.9316 7.96195 18.5039 7.22223 20L9.73023 19.1581C10.4824 18.9058 11.2954 18.9058 12.0476 19.1581C12.8615 19.4309 13.6585 19.7588 14.5346 19.6962C15.439 19.6315 16.2086 19.1677 17 18.7691"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-line"
			d="M6 13H12"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
		/>
	</g>
</svg>
