<!-- ! This file is automatically generated, please don't edit it directly. -->

<script lang="ts">
	export let size = 24;
	export let color = 'currentColor';
	export let strokeWidth = 2;
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-radio-off">
		<circle
			class="oi-ellipse"
			cx="12"
			cy="12"
			r="6"
			stroke={color}
			stroke-width={strokeWidth}
		/>
	</g>
</svg>
