<!-- ! This file is automatically generated, please don't edit it directly. -->

<script lang="ts">
	export let size = 24;
	export let color = 'currentColor';
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-server-fill">
		<path
			class="oi-fill"
			d="M21 1C22.1046 1 23 1.89543 23 3V9C23 10.1046 22.1046 11 21 11H3C1.89543 11 1 10.1046 1 9V3C1 1.89543 1.89543 1 3 1H21ZM6 4.5C5.17157 4.5 4.5 5.17157 4.5 6C4.5 6.82843 5.17157 7.5 6 7.5H6.00977C6.83819 7.5 7.50977 6.82843 7.50977 6C7.50977 5.17157 6.83819 4.5 6.00977 4.5H6Z"
			fill={color}
		/>
		<path
			class="oi-fill"
			d="M21 13C22.1046 13 23 13.8954 23 15V21C23 22.1046 22.1046 23 21 23H3C1.89543 23 1 22.1046 1 21V15C1 13.8954 1.89543 13 3 13H21ZM6 16.5C5.17157 16.5 4.5 17.1716 4.5 18C4.5 18.8284 5.17157 19.5 6 19.5H6.00977C6.83819 19.5 7.50977 18.8284 7.50977 18C7.50977 17.1716 6.83819 16.5 6.00977 16.5H6Z"
			fill={color}
		/>
	</g>
</svg>
