<!-- ! This file is automatically generated, please don't edit it directly. -->

<script lang="ts">
	export let size = 24;
	export let color = 'currentColor';
	export let strokeWidth = 2;
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-shopping-cart">
		<path
			class="oi-medium-dot"
			d="M10 20H10.012"
			stroke={color}
			stroke-width={strokeWidth * 1.5}
			stroke-linecap="round"
		/>
		<path
			class="oi-medium-dot"
			d="M18.4902 20.0264H18.5022"
			stroke={color}
			stroke-width={strokeWidth * 1.5}
			stroke-linecap="round"
		/>
		<path
			class="oi-vector"
			d="M1.99961 2H5.99961L8.67961 14.39C8.77105 14.8504 9.02152 15.264 9.38715 15.5583C9.75279 15.8526 10.2103 16.009 10.6796 16H18.3996C18.8689 16.009 19.3264 15.8526 19.6921 15.5583C20.0577 15.264 20.3082 14.8504 20.3996 14.39L21.9996 7H7.08112"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
	</g>
</svg>
