<!-- ! This file is automatically generated, please don't edit it directly. -->

<script lang="ts">
	export let size = 24;
	export let color = 'currentColor';
	export let strokeWidth = 2;
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-suitcase">
		<rect
			class="oi-box"
			x="6"
			y="5"
			width="12"
			height="15"
			rx="2"
			stroke={color}
			stroke-width={strokeWidth}
		/>
		<path
			class="oi-line"
			d="M10 8L14 8"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-line"
			d="M8.5 20V21.5"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
		/>
		<path
			class="oi-line"
			d="M15.5 20V21.5"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
		/>
		<path
			class="oi-line"
			d="M12 3V5"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
		/>
	</g>
</svg>
