<!-- ! This file is automatically generated, please don't edit it directly. -->

<script lang="ts">
	export let size = 24;
	export let color = 'currentColor';
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-tag-fill">
		<path
			class="oi-fill"
			d="M12.3724 3.54456C13.274 3.54462 14.1382 3.90319 14.7757 4.54065L22.1781 11.942C23.5058 13.2697 23.5057 15.4228 22.1781 16.7506L16.6615 22.2672C15.3337 23.5948 13.1806 23.5949 11.8529 22.2672L4.45153 14.8658C3.81396 14.2282 3.45543 13.3623 3.45543 12.4606V6.94495C3.45544 5.06719 4.97806 3.54456 6.85582 3.54456H12.3724ZM8.49352 6.98499C7.66529 6.98512 6.99364 7.65675 6.99352 8.48499C6.99352 9.31333 7.66521 9.98485 8.49352 9.98499H8.50524C9.33366 9.98499 10.0052 9.31341 10.0052 8.48499C10.0051 7.65667 9.33359 6.98499 8.50524 6.98499H8.49352Z"
			fill={color}
		/>
	</g>
</svg>
