<!-- ! This file is automatically generated, please don't edit it directly. -->

<svelte:options namespace="svg" />

<script lang="ts">
  export let size = 24
  export let color = 'currentColor'
  export let strokeWidth = 2
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-tractor">
		<path
			class="oi-ellipse"
			d="M19.875 20.25C21.3247 20.25 22.5 19.0747 22.5 17.625C22.5 16.1753 21.3247 15 19.875 15C18.4253 15 17.25 16.1753 17.25 17.625C17.25 19.0747 18.4253 20.25 19.875 20.25Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-ellipse"
			d="M6.375 20.25C8.65317 20.25 10.5 18.4032 10.5 16.125C10.5 13.8468 8.65317 12 6.375 12C4.09683 12 2.25 13.8468 2.25 16.125C2.25 18.4032 4.09683 20.25 6.375 20.25Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-ellipse"
			d="M6.5 16.125C6.5 16.194 6.44404 16.25 6.375 16.25C6.30596 16.25 6.25 16.194 6.25 16.125C6.25 16.056 6.30596 16 6.375 16C6.44404 16 6.5 16.056 6.5 16.125Z"
			fill="#504DCB"
			stroke={color}
			stroke-width={strokeWidth}
		/>
		<path
			class="oi-vector"
			d="M21.75 15.75V12.5625C21.75 12.4013 21.6979 12.2443 21.6017 12.115C21.5054 11.9856 21.3701 11.8907 21.2156 11.8444L13.5 9.75V4.5H5.25V9"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-line"
			d="M3.75 4.5H5.25"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-line"
			d="M13.5 4.5H15"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M3.75 9H6.375C8.26467 9 10.0769 9.75067 11.4131 11.0869C12.7493 12.4231 13.5 14.2353 13.5 16.125V17.25H17.2762"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-line"
			d="M13.5 9.75V17.25"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-line"
			d="M17.25 10.7653V6.75"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
	</g>
</svg>
