<!-- ! This file is automatically generated, please don't edit it directly. -->

<script lang="ts">
	export let size = 24;
	export let color = 'currentColor';
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-user-encircled-alt-2-fill">
		<path
			class="oi-fill"
			d="M12 2C17.5228 2 22 6.47715 22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12C2 6.47715 6.47715 2 12 2ZM8 15C6.88439 15.0001 5.91236 15.61 5.39551 16.5137C6.83666 18.6183 9.25666 20 12 20C14.7432 19.9999 17.1623 18.6181 18.6035 16.5137C18.0866 15.6102 17.1155 15.0001 16 15H8ZM12 5C9.79093 5.00008 8 6.79091 8 9C8 11.2091 9.79093 12.9999 12 13C14.2091 12.9999 16 11.2091 16 9C16 6.79091 14.2091 5.00008 12 5Z"
			fill={color}
		/>
	</g>
</svg>
