<!-- ! This file is automatically generated, please don't edit it directly. -->

<script lang="ts">
	export let size = 24;
	export let color = 'currentColor';
	export let strokeWidth = 2;
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-vegan">
		<path
			class="oi-vector"
			d="M19.6542 7.26579C20.7925 9.10615 21.2306 11.297 20.8846 13.4367C20.5301 15.6289 19.3776 17.6127 17.6488 19.0065C15.9199 20.4003 13.7368 21.1058 11.5193 20.9871C9.30173 20.8685 7.20633 19.9342 5.63604 18.364C4.06576 16.7937 3.13147 14.6983 3.01286 12.4807C2.89424 10.2632 3.59967 8.08008 4.99348 6.35124C6.3873 4.62241 8.37108 3.46993 10.5633 3.11543C12.6893 2.77165 14.8658 3.2019 16.6988 4.32402"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M3.00012 3C5.71693 5.16724 7.92931 7.89998 9.48354 11.0084C11.0378 14.1168 11.8966 17.5263 12.0004 21C12.8104 14.862 13.3504 12.45 15.6004 8.4"
			stroke={color}
			stroke-width="1.80002"
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M15.5997 8.4C19.1998 8.4 20.9999 6.6 20.9999 3C17.3998 3 15.5997 4.8 15.5997 8.4Z"
			stroke={color}
			stroke-width="1.80002"
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
	</g>
</svg>
