<!-- ! This file is automatically generated, please don't edit it directly. -->

<script lang="ts">
	export let size = 24;
	export let color = 'currentColor';
	export let strokeWidth = 2;
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-washing-machine">
		<path
			class="oi-line"
			d="M4 7H7"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-mini-dot"
			d="M16.5833 7H16.5933"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-box"
			d="M18.2222 3H5.77778C4.79594 3 4 3.80589 4 4.8V19.2C4 20.1941 4.79594 21 5.77778 21H18.2222C19.2041 21 20 20.1941 20 19.2V4.8C20 3.80589 19.2041 3 18.2222 3Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-ellipse"
			d="M12 18C14.5313 18 16.5833 15.948 16.5833 13.4167C16.5833 10.8854 14.5313 8.83334 12 8.83334C9.46868 8.83334 7.41666 10.8854 7.41666 13.4167C7.41666 15.948 9.46868 18 12 18Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M12 18C12.6078 18 13.1907 17.7586 13.6205 17.3288C14.0502 16.899 14.2917 16.3161 14.2917 15.7083C14.2917 15.1006 14.0502 14.5177 13.6205 14.0879C13.1907 13.6581 12.6078 13.4167 12 13.4167C11.3922 13.4167 10.8093 13.1752 10.3796 12.7455C9.94979 12.3157 9.70834 11.7328 9.70834 11.125C9.70834 10.5172 9.94979 9.93433 10.3796 9.50456C10.8093 9.07479 11.3922 8.83334 12 8.83334"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
	</g>
</svg>
