<!-- ! This file is automatically generated, please don't edit it directly. -->

<script lang="ts">
	export let size = 24;
	export let color = 'currentColor';
	export let strokeWidth = 2;
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-wheelchair-alt" clip-path="url(#clip0_794_56478)">
		<path
			class="oi-vector"
			d="M9.75 6.75V12.75H18L21 18.75L23.25 18"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-ellipse"
			d="M9.75 6.75C10.9926 6.75 12 5.74264 12 4.5C12 3.25736 10.9926 2.25 9.75 2.25C8.50736 2.25 7.5 3.25736 7.5 4.5C7.5 5.74264 8.50736 6.75 9.75 6.75Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M15.75 9H10.5C8.9087 9 7.38258 9.63214 6.25736 10.7574C5.13214 11.8826 4.5 13.4087 4.5 15C4.5 16.5913 5.13214 18.1174 6.25736 19.2426C7.38258 20.3679 8.9087 21 10.5 21C13.2956 21 15.8344 19.0875 16.5 16.5"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
	</g>
	<defs>
		<clipPath class="clip0_794_56478">
			<rect width={size} height={size} fill="white" />
		</clipPath>
	</defs>
</svg>
