<!-- ! This file is automatically generated, please don't edit it directly. -->

<script lang="ts">
	export let size = 24;
	export let color = 'currentColor';
	export let strokeWidth = 2;
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-wine">
		<path
			class="oi-line"
			d="M12 17.25V22.5"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-line"
			d="M8.25 22.5H15.75"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M7.50842 3H16.4915L18.5344 9.93094C18.8109 10.8602 18.8239 11.848 18.572 12.7843C18.32 13.7205 17.813 14.5684 17.1075 15.2334C15.7221 16.53 13.8956 17.2513 11.9981 17.2513C10.1006 17.2513 8.27415 16.53 6.88874 15.2334C6.18403 14.5679 5.67788 13.7198 5.42662 12.7836C5.17536 11.8474 5.18886 10.8599 5.46561 9.93094L7.50842 3Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M5.61188 9.43307C6.79594 8.92588 8.925 8.56869 12 10.1249C15.3619 11.8274 17.5941 11.2396 18.6956 10.6724"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
	</g>
</svg>
