import { icons as productIcons, type NamedIcon } from './icons';
import {
	IconBarChart,
	IconPieChartSinglePart,
	IconLineChartUp,
	IconBriefcase,
	IconBankCard,
	IconCoin,
	IconReceipt,
	IconInvoice,
	IconCalculator,
	IconBudget,
	IconSavings,
	IconCircleDollar,
	IconDiscount,
	IconShoppingCart,
	IconShoppingBasket,
	IconStore,
	IconTarget,
	IconRanking,
	IconTrendingUp,
	IconStatisticUp,
	IconCollaboration,
	IconSignature,
	IconGavel,
	IconVault,
	IconBank,
	IconOffice,
	IconPresentation,
	IconKanban,
	IconTaskList,
	IconChecklist,
	IconClipboardCheck,
	IconSitemap,
	IconWorkflow,
	IconGanttChart,
	IconTimer,
	IconRoute,
	IconSuitcase,
	IconPassport,
	IconPieChart3Parts,
	IconCircleEuro,
	IconCpu,
	IconDatabase,
	IconTerminal,
	IconCode,
	IconCodeBranch,
	IconRobot,
	IconMachineLearning,
	IconMagicWandAi,
	IconFingerprint,
	IconQrCodeScan,
	IconBarcodeScan,
	IconWebhook,
	IconServer,
	IconCast,
	IconBluetooth,
	IconSignal,
	IconBatteryCharging,
	IconPowerOff,
	IconDevices,
	IconComputerMonitor,
	IconGameController,
	IconJoystick,
	IconVideoCamera,
	IconWebcam,
	IconMic,
	IconHeadphones,
	IconSpeakers,
	IconVolume2,
	IconRadio,
	IconSatellite,
	IconDrone,
	IconAugmentedReality,
	IconAtom,
	IconDna,
	IconCircuitry,
	IconHeadCircuit,
	IconPrism,
	IconBezierCurve,
	IconSphere,
	IconCubeOnAxis,
	IconBankTransactions,
	IconCards,
	IconWallet,
	IconDocument,
	IconDocumentCheck,
	IconFolderUser,
	IconOfficeChair,
	IconJustice,
	IconDashboard,
	IconFunnelAscending,
	IconBug,
	IconKeyboard,
	IconMouse,
	IconSolarPanel,
	IconCloudDeploy,
	IconAirplay,
	IconBolt,
	IconRss,
	IconWrench,
	IconBatteryFull,
} from 'obra-icons-svelte';

export type CompositionVariant = {
	name: string;
	icons: NamedIcon[];
};

const businessIcons: NamedIcon[] = [
	{ name: 'Bar Chart', Icon: IconBarChart },
	{ name: 'Pie Chart', Icon: IconPieChartSinglePart },
	{ name: 'Line Chart Up', Icon: IconLineChartUp },
	{ name: 'Briefcase', Icon: IconBriefcase },
	{ name: 'Bank Card', Icon: IconBankCard },
	{ name: 'Coin', Icon: IconCoin },
	{ name: 'Receipt', Icon: IconReceipt },
	{ name: 'Invoice', Icon: IconInvoice },
	{ name: 'Calculator', Icon: IconCalculator },
	{ name: 'Budget', Icon: IconBudget },
	{ name: 'Savings', Icon: IconSavings },
	{ name: 'Circle Dollar', Icon: IconCircleDollar },
	{ name: 'Discount', Icon: IconDiscount },
	{ name: 'Shopping Cart', Icon: IconShoppingCart },
	{ name: 'Shopping Basket', Icon: IconShoppingBasket },
	{ name: 'Store', Icon: IconStore },
	{ name: 'Target', Icon: IconTarget },
	{ name: 'Ranking', Icon: IconRanking },
	{ name: 'Trending Up', Icon: IconTrendingUp },
	{ name: 'Statistic Up', Icon: IconStatisticUp },
	{ name: 'Collaboration', Icon: IconCollaboration },
	{ name: 'Signature', Icon: IconSignature },
	{ name: 'Gavel', Icon: IconGavel },
	{ name: 'Vault', Icon: IconVault },
	{ name: 'Bank', Icon: IconBank },
	{ name: 'Office', Icon: IconOffice },
	{ name: 'Presentation', Icon: IconPresentation },
	{ name: 'Kanban', Icon: IconKanban },
	{ name: 'Task List', Icon: IconTaskList },
	{ name: 'Checklist', Icon: IconChecklist },
	{ name: 'Clipboard Check', Icon: IconClipboardCheck },
	{ name: 'Sitemap', Icon: IconSitemap },
	{ name: 'Workflow', Icon: IconWorkflow },
	{ name: 'Gantt Chart', Icon: IconGanttChart },
	{ name: 'Timer', Icon: IconTimer },
	{ name: 'Route', Icon: IconRoute },
	{ name: 'Suitcase', Icon: IconSuitcase },
	{ name: 'Passport', Icon: IconPassport },
	{ name: 'Pie Chart 3 Parts', Icon: IconPieChart3Parts },
	{ name: 'Circle Euro', Icon: IconCircleEuro },
	{ name: 'Bank Transactions', Icon: IconBankTransactions },
	{ name: 'Cards', Icon: IconCards },
	{ name: 'Wallet', Icon: IconWallet },
	{ name: 'Document', Icon: IconDocument },
	{ name: 'Document Check', Icon: IconDocumentCheck },
	{ name: 'Folder User', Icon: IconFolderUser },
	{ name: 'Office Chair', Icon: IconOfficeChair },
	{ name: 'Justice', Icon: IconJustice },
	{ name: 'Dashboard', Icon: IconDashboard },
	{ name: 'Funnel Ascending', Icon: IconFunnelAscending },
];

const techIcons: NamedIcon[] = [
	{ name: 'CPU', Icon: IconCpu },
	{ name: 'Database', Icon: IconDatabase },
	{ name: 'Terminal', Icon: IconTerminal },
	{ name: 'Code', Icon: IconCode },
	{ name: 'Code Branch', Icon: IconCodeBranch },
	{ name: 'Robot', Icon: IconRobot },
	{ name: 'Machine Learning', Icon: IconMachineLearning },
	{ name: 'Magic Wand AI', Icon: IconMagicWandAi },
	{ name: 'Fingerprint', Icon: IconFingerprint },
	{ name: 'QR Code Scan', Icon: IconQrCodeScan },
	{ name: 'Barcode Scan', Icon: IconBarcodeScan },
	{ name: 'Webhook', Icon: IconWebhook },
	{ name: 'Server', Icon: IconServer },
	{ name: 'Cast', Icon: IconCast },
	{ name: 'Bluetooth', Icon: IconBluetooth },
	{ name: 'Signal', Icon: IconSignal },
	{ name: 'Battery Charging', Icon: IconBatteryCharging },
	{ name: 'Power Off', Icon: IconPowerOff },
	{ name: 'Devices', Icon: IconDevices },
	{ name: 'Computer Monitor', Icon: IconComputerMonitor },
	{ name: 'Game Controller', Icon: IconGameController },
	{ name: 'Joystick', Icon: IconJoystick },
	{ name: 'Video Camera', Icon: IconVideoCamera },
	{ name: 'Webcam', Icon: IconWebcam },
	{ name: 'Mic', Icon: IconMic },
	{ name: 'Headphones', Icon: IconHeadphones },
	{ name: 'Speakers', Icon: IconSpeakers },
	{ name: 'Volume', Icon: IconVolume2 },
	{ name: 'Radio', Icon: IconRadio },
	{ name: 'Satellite', Icon: IconSatellite },
	{ name: 'Drone', Icon: IconDrone },
	{ name: 'Augmented Reality', Icon: IconAugmentedReality },
	{ name: 'Atom', Icon: IconAtom },
	{ name: 'DNA', Icon: IconDna },
	{ name: 'Circuitry', Icon: IconCircuitry },
	{ name: 'Head Circuit', Icon: IconHeadCircuit },
	{ name: 'Prism', Icon: IconPrism },
	{ name: 'Bezier Curve', Icon: IconBezierCurve },
	{ name: 'Sphere', Icon: IconSphere },
	{ name: 'Cube On Axis', Icon: IconCubeOnAxis },
	{ name: 'Bug', Icon: IconBug },
	{ name: 'Keyboard', Icon: IconKeyboard },
	{ name: 'Mouse', Icon: IconMouse },
	{ name: 'Solar Panel', Icon: IconSolarPanel },
	{ name: 'Cloud Deploy', Icon: IconCloudDeploy },
	{ name: 'Airplay', Icon: IconAirplay },
	{ name: 'Bolt', Icon: IconBolt },
	{ name: 'RSS', Icon: IconRss },
	{ name: 'Wrench', Icon: IconWrench },
	{ name: 'Battery Full', Icon: IconBatteryFull },
];

/** Alternate 50-icon selections for the composition view, so a few options can be compared. */
export const compositionVariants: CompositionVariant[] = [
	{ name: 'Variant 1 — Product', icons: productIcons },
	{ name: 'Variant 2 — Business', icons: businessIcons },
	{ name: 'Variant 3 — Tech', icons: techIcons },
];
