import {
	IconHome,
	IconSearch,
	IconSettings,
	IconUser,
	IconHeart,
	IconFavorite,
	IconNotification,
	IconCalendarDates,
	IconCamera,
	IconChatAi,
	IconCheck,
	IconClock3,
	IconCloud,
	IconDownload,
	IconUpload,
	IconMailbox,
	IconFolder,
	IconGift,
	IconGlobe,
	IconImage,
	IconKey,
	IconLock,
	IconMap,
	IconMoon,
	IconSun,
	IconPhone,
	IconPlay,
	IconAdd,
	IconDelete,
	IconWallet,
	IconWifi,
	IconCompass,
	IconBook,
	IconBookmark,
	IconFlag,
	IconLink,
	IconLightbulb,
	IconRocketShip,
	IconShield,
	IconTag,
	IconEdit,
	IconShare,
	IconFilter,
	IconMessage,
	IconInbox,
	IconLocation,
	IconUsers,
	IconSend,
	IconPuzzlePiece,
	IconArchiveBox,
} from 'obra-icons-svelte';

export type NamedIcon = {
	name: string;
	Icon: typeof IconHome;
};

/** The 50-icon set used in the composition and zoom views. */
export const icons: NamedIcon[] = [
	{ name: 'Home', Icon: IconHome },
	{ name: 'Search', Icon: IconSearch },
	{ name: 'Settings', Icon: IconSettings },
	{ name: 'User', Icon: IconUser },
	{ name: 'Heart', Icon: IconHeart },
	{ name: 'Favorite', Icon: IconFavorite },
	{ name: 'Notification', Icon: IconNotification },
	{ name: 'Calendar', Icon: IconCalendarDates },
	{ name: 'Camera', Icon: IconCamera },
	{ name: 'Chat AI', Icon: IconChatAi },
	{ name: 'Check', Icon: IconCheck },
	{ name: 'Clock', Icon: IconClock3 },
	{ name: 'Cloud', Icon: IconCloud },
	{ name: 'Download', Icon: IconDownload },
	{ name: 'Upload', Icon: IconUpload },
	{ name: 'Mailbox', Icon: IconMailbox },
	{ name: 'Folder', Icon: IconFolder },
	{ name: 'Gift', Icon: IconGift },
	{ name: 'Globe', Icon: IconGlobe },
	{ name: 'Image', Icon: IconImage },
	{ name: 'Key', Icon: IconKey },
	{ name: 'Lock', Icon: IconLock },
	{ name: 'Map', Icon: IconMap },
	{ name: 'Moon', Icon: IconMoon },
	{ name: 'Sun', Icon: IconSun },
	{ name: 'Phone', Icon: IconPhone },
	{ name: 'Play', Icon: IconPlay },
	{ name: 'Add', Icon: IconAdd },
	{ name: 'Delete', Icon: IconDelete },
	{ name: 'Wallet', Icon: IconWallet },
	{ name: 'Wifi', Icon: IconWifi },
	{ name: 'Compass', Icon: IconCompass },
	{ name: 'Book', Icon: IconBook },
	{ name: 'Bookmark', Icon: IconBookmark },
	{ name: 'Flag', Icon: IconFlag },
	{ name: 'Link', Icon: IconLink },
	{ name: 'Lightbulb', Icon: IconLightbulb },
	{ name: 'Rocket Ship', Icon: IconRocketShip },
	{ name: 'Shield', Icon: IconShield },
	{ name: 'Tag', Icon: IconTag },
	{ name: 'Edit', Icon: IconEdit },
	{ name: 'Share', Icon: IconShare },
	{ name: 'Filter', Icon: IconFilter },
	{ name: 'Message', Icon: IconMessage },
	{ name: 'Inbox', Icon: IconInbox },
	{ name: 'Location', Icon: IconLocation },
	{ name: 'Users', Icon: IconUsers },
	{ name: 'Send', Icon: IconSend },
	{ name: 'Puzzle Piece', Icon: IconPuzzlePiece },
	{ name: 'Archive Box', Icon: IconArchiveBox },
];

/** The icon choices offered in the weights (grid construction) view. */
export const zoomIcons: NamedIcon[] = [
	{ name: 'Mailbox', Icon: IconMailbox },
	{ name: 'Home', Icon: IconHome },
	{ name: 'Bookmark', Icon: IconBookmark },
	{ name: 'Rocket Ship', Icon: IconRocketShip },
];
