<!-- ! This file is automatically generated, please don't edit it directly. -->

<svelte:options namespace="svg" />

<script lang="ts">
  export let size = 24
  export let color = 'currentColor'
  // svelte-ignore unused-export-let
  export let strokeWidth = 2
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-closed-captioning">
		<path
			class="oi-vector"
			d="M10.7396 10.4648C10.2872 9.98154 9.6459 9.67987 8.93464 9.67987C7.56464 9.67987 6.45404 10.7991 6.45404 12.1798C6.45404 13.5604 7.56464 14.6796 8.93464 14.6796C9.46998 14.6796 9.96571 14.5087 10.371 14.2181"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
		/>
		<path
			class="oi-box"
			d="M20 5H4C3.44772 5 3 5.44772 3 6V18C3 18.5523 3.44772 19 4 19H20C20.5523 19 21 18.5523 21 18V6C21 5.44772 20.5523 5 20 5Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-miterlimit="10"
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M17.546 10.4648C17.0936 9.98154 16.4523 9.67987 15.741 9.67987C14.371 9.67987 13.2604 10.7991 13.2604 12.1798C13.2604 13.5604 14.371 14.6796 15.741 14.6796C16.2764 14.6796 16.7721 14.5087 17.1774 14.2181"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
		/>
	</g>
</svg>
