<!-- ! This file is automatically generated, please don't edit it directly. -->

<svelte:options namespace="svg" />

<script lang="ts">
  export let size = 24
  export let color = 'currentColor'
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-crown-fill">
		<path
			class="oi-line"
			d="M5 20H19"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
		/>
		<path
			class="oi-fill"
			d="M12 0.984436L7.71182 8.48881L1.49829 3.51798L4.12182 17H19.3535L22.6646 3.38771L16.2882 8.48881L12 0.984436Z"
			fill={color}
		/>
	</g>
</svg>
