<!-- ! This file is automatically generated, please don't edit it directly. -->

<svelte:options namespace="svg" />

<script lang="ts">
  export let size = 24
  export let color = 'currentColor'
  // svelte-ignore unused-export-let
  export let strokeWidth = 2
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-damages-warning[insurance,broken-window]">
		<path
			class="oi-vector"
			d="M10 20H5C3.89543 20 3 19.1046 3 18V5C3 3.89543 3.89543 3 5 3H7.77773L6.4963 7.2714C6.44042 7.45767 6.57991 7.64516 6.77439 7.64516H8.91557C9.10445 7.64516 9.24304 7.82266 9.19722 8.00592L8.40363 11.1802C8.3306 11.4724 8.69581 11.6689 8.8993 11.4469L14.0673 5.8091C14.2379 5.62289 14.1058 5.32258 13.8533 5.32258H11.6624C11.483 5.32258 11.3465 5.16149 11.376 4.98453L11.7068 3H19C20.1046 3 21 3.89543 21 5V19.5"
			stroke={color}
			stroke-width={strokeWidth}
		/>
		<path
			class="oi-triangle"
			d="M15.2079 10.945C15.5078 10.3751 16.3238 10.3751 16.6237 10.945L21.6145 20.4273C21.8948 20.96 21.5085 21.5999 20.9065 21.5999H10.9251C10.3231 21.5999 9.93679 20.96 10.2172 20.4273L15.2079 10.945Z"
			fill="white"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-miterlimit="10"
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-line"
			d="M15.9158 16.6526V15.6526"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-line"
			d="M15.9158 19.0737H15.9224"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
		/>
	</g>
</svg>
