<!-- ! This file is automatically generated, please don't edit it directly. -->

<svelte:options namespace="svg" />

<script lang="ts">
  export let size = 24
  export let color = 'currentColor'
  export let strokeWidth = 2
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-document-pdf">
		<path
			class="oi-box"
			d="M17 11V8L12 3H4C3.44772 3 3 3.44772 3 4V20C3 20.5523 3.44772 21 4 21H16C16.5523 21 17 20.5523 17 20V20"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-miterlimit="10"
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-line"
			d="M11 3V9H17"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-miterlimit="10"
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M7.23038 17.7826L7.23038 15.5631M7.23038 15.5631L7.23038 13.0168C7.69491 13.0168 9.12316 13.0168 9.55304 13.0168C10.355 13.0168 10.7657 13.7012 10.7657 14.3568C10.7657 14.9602 10.1202 15.4331 9.59451 15.5227C9.44737 15.5477 9.10561 15.5704 8.95521 15.5631H7.23038Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-miterlimit="2.16568"
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M13.1298 17.7128V13.0168H14.7292C16.1266 13.0168 16.9965 14.3093 16.9965 15.3658C16.9965 16.6863 16.2238 17.7128 14.7292 17.7128H13.1298Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-miterlimit="2.16568"
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M19.9396 17.6281V15.2143M19.9396 15.2143V13.0168C20.4032 13.0168 22.4667 13.0168 22.8957 13.0168M19.9396 15.2143H22.8957"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-miterlimit="2.16568"
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
	</g>
</svg>
