<!-- ! This file is automatically generated, please don't edit it directly. -->

<svelte:options namespace="svg" />

<script lang="ts">
  export let size = 24
  export let color = 'currentColor'
  export let strokeWidth = 2
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-electric-car-charging">
		<path
			class="oi-vector"
			d="M3.93333 12.3814H4.86667L7.2 15.239H12.8L15.1333 12.3814C15.1333 12.3814 15.7022 12.3814 16.0667 12.3814M3.93333 12.3814H3V20.4306C4.50275 21.2255 5.31231 21.1533 6.73333 20.4306L7.2 19.0492H12.8L13.2667 20.4306C14.6877 21.1533 15.4972 21.2255 17 20.4306V12.3814C17 12.3814 16.4312 12.3814 16.0667 12.3814M3.93333 12.3814V9.5H16.0667C16.0667 9.5 16.0667 11.2561 16.0667 12.3814"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M21 7V20M21 20L19.5 21M21 20L22.5 21"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M19 2.5L21 2L23 2.5V7H19V2.5Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
	</g>
</svg>
