<!-- ! This file is automatically generated, please don't edit it directly. -->

<svelte:options namespace="svg" />

<script lang="ts">
  export let size = 24
  export let color = 'currentColor'
  export let strokeWidth = 2
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-grain">
		<path
			class="oi-vector"
			d="M15.7839 12.8418L16.4694 12.8364C17.0278 12.832 17.4816 13.2858 17.4772 13.8442L17.4718 14.5297C17.4544 16.739 15.6493 18.5158 13.44 18.4981L12.8124 18.4931C12.2664 18.4888 11.8248 18.0472 11.8205 17.5011L11.8154 16.8736C11.7978 14.6643 13.5746 12.8591 15.7839 12.8418Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M15.7839 7.84179L16.4694 7.83641C17.0278 7.83202 17.4816 8.28582 17.4772 8.84423L17.4718 9.52969C17.4544 11.739 15.6493 13.5158 13.44 13.4981L12.8124 13.4931C12.2664 13.4888 11.8248 13.0472 11.8205 12.5011L11.8154 11.8736C11.7978 9.66432 13.5746 7.85915 15.7839 7.84179Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M8.52957 12.8418L7.84411 12.8364C7.2857 12.832 6.8319 13.2858 6.83629 13.8442L6.84167 14.5297C6.85903 16.739 8.66421 18.5158 10.8735 18.4981L11.501 18.4931C12.0471 18.4888 12.4887 18.0472 12.493 17.5011L12.498 16.8736C12.5157 14.6643 10.7388 12.8591 8.52957 12.8418Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M8.52957 7.84179L7.84411 7.83641C7.2857 7.83202 6.8319 8.28582 6.83629 8.84423L6.84167 9.52969C6.85903 11.739 8.66421 13.5158 10.8735 13.4981L11.501 13.4931C12.0471 13.4888 12.4887 13.0472 12.493 12.5011L12.498 11.8736C12.5157 9.66432 10.7388 7.85915 8.52957 7.84179Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M10.8065 2.85622L11.2874 2.36772C11.6791 1.96976 12.3209 1.96976 12.7126 2.36772L13.1935 2.85622C14.7434 4.43068 14.7234 6.96354 13.1487 8.51326L12.7014 8.95346C12.3122 9.33649 11.6878 9.33649 11.2986 8.95346L10.8513 8.51326C9.27661 6.96354 9.25656 4.43068 10.8065 2.85622Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M12 9L12 21"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
	</g>
</svg>
