<!-- ! This file is automatically generated, please don't edit it directly. -->

<svelte:options namespace="svg" />

<script lang="ts">
  export let size = 24
  export let color = 'currentColor'
  export let strokeWidth = 2
</script>

<svg
	width={size}
	height="25"
	viewBox="0 0 24 25"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-invoices">
		<path
			class="oi-line"
			d="M7 6.5L11 6.5"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-line"
			d="M14 18.5L17 18.5"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<rect
			id="Rectangle 959"
			x="4"
			y="3.5"
			width="16"
			height="18"
			rx="2"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-miterlimit="10"
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M13.75 14.5H15.5C16.6046 14.5 17.5 13.6046 17.5 12.5V11.5C17.5 10.3954 16.6046 9.5 15.5 9.5H13.75M13.75 14.5H9C7.89543 14.5 7 13.6046 7 12.5V11.5C7 10.3954 7.89543 9.5 9 9.5H13.75M13.75 14.5V9.5"
			stroke={color}
			stroke-width={strokeWidth}
		/>
	</g>
</svg>
