<!-- ! This file is automatically generated, please don't edit it directly. -->

<svelte:options namespace="svg" />

<script lang="ts">
  export let size = 24
  export let color = 'currentColor'
  export let strokeWidth = 2
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-joystick" clip-path="url(#clip0_642_111718)">
		<path
			class="oi-vector"
			d="M12.071 10L21.1421 13.0711L12.071 16.1421L2.99998 13.0711L12.071 10Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M21.1421 13.0711L21.1421 18.3539C21.1421 18.7826 20.8689 19.1636 20.4628 19.3011L12.7124 21.925C12.2964 22.0658 11.8457 22.0658 11.4297 21.925L3.6793 19.3011C3.27324 19.1636 2.99998 18.7826 2.99998 18.3539L2.99998 13.0711"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<circle
			class="oi-ellipse"
			cx="12"
			cy="5"
			r="3"
			stroke={color}
			stroke-width={strokeWidth}
		/>
		<path
			class="oi-line"
			d="M12.071 12.5V8"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
		/>
	</g>
	<defs>
		<clipPath class="clip0_642_111718">
			<rect width={size} height={size} fill="white" />
		</clipPath>
	</defs>
</svg>
