<!-- ! This file is automatically generated, please don't edit it directly. -->

<svelte:options namespace="svg" />

<script lang="ts">
  export let size = 24
  export let color = 'currentColor'
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-message-circle-fill">
		<path
			class="oi-fill"
			fill-rule="evenodd"
			clip-rule="evenodd"
			d="M3.00001 11.1818C3.00001 6.13214 7.00838 2 12 2C16.9916 2 21 6.13214 21 11.1818C21 16.2315 16.9916 20.3636 12 20.3636C10.886 20.3636 9.81769 20.1567 8.83134 19.7781L4.43475 21.9006C4.07389 22.0748 3.6439 22.0167 3.34213 21.7531C3.04035 21.4895 2.92507 21.0712 3.0492 20.6902L4.49531 16.2517C3.54979 14.7975 3.00001 13.0532 3.00001 11.1818Z"
			fill={color}
		/>
	</g>
</svg>
