<!-- ! This file is automatically generated, please don't edit it directly. -->

<svelte:options namespace="svg" />

<script lang="ts">
  export let size = 24
  export let color = 'currentColor'
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-next-fill">
		<path
			class="oi-vector"
			d="M18 7V17"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-miterlimit="10"
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-fill"
			d="M8.02899 6.05116C6.69594 5.25134 5 6.21156 5 7.76615V16.2338C5 17.7884 6.69595 18.7486 8.02899 17.9488L15.0853 13.7149C16.38 12.9381 16.38 11.0618 15.0853 10.285L8.02899 6.05116Z"
			fill={color}
		/>
	</g>
</svg>
