<!-- ! This file is automatically generated, please don't edit it directly. -->

<svelte:options namespace="svg" />

<script lang="ts">
  export let size = 24
  export let color = 'currentColor'
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-paint-roller-fill">
		<path
			class="oi-fill"
			fill-rule="evenodd"
			clip-rule="evenodd"
			d="M4 5C4 3.34315 5.34315 2 7 2H17C18.6569 2 20 3.34315 20 5V5.17071C21.1652 5.58254 22 6.69378 22 8V10C22 11.6569 20.6569 13 19 13H14C13.4477 13 13 13.4477 13 14C14.1046 14 15 14.8954 15 16V20C15 21.1046 14.1046 22 13 22H11C9.89543 22 9 21.1046 9 20V16C9 14.8954 9.89543 14 11 14C11 12.3431 12.3431 11 14 11H19C19.5523 11 20 10.5523 20 10V8C20 7.87205 19.976 7.74972 19.9322 7.63726C19.64 8.988 18.4382 10 17 10H7C5.34315 10 4 8.65685 4 7V5Z"
			fill={color}
		/>
	</g>
</svg>
