<!-- ! This file is automatically generated, please don't edit it directly. -->

<svelte:options namespace="svg" />

<script lang="ts">
  export let size = 24
  export let color = 'currentColor'
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-shapes-fill">
		<path
			class="oi-fill"
			fill-rule="evenodd"
			clip-rule="evenodd"
			d="M12 3C12.3557 3 12.6846 3.18891 12.8638 3.49613L16.3638 9.49613C16.5442 9.80542 16.5455 10.1876 16.3671 10.4981C16.1888 10.8086 15.8581 11 15.5 11H8.5C8.14193 11 7.8112 10.8086 7.63286 10.4981C7.45452 10.1876 7.4558 9.80542 7.63622 9.49613L11.1362 3.49613C11.3154 3.18891 11.6443 3 12 3ZM17 12.5C14.5147 12.5 12.5 14.5147 12.5 17C12.5 19.4853 14.5147 21.5 17 21.5C19.4853 21.5 21.5 19.4853 21.5 17C21.5 14.5147 19.4853 12.5 17 12.5ZM3 14C3 13.4477 3.44772 13 4 13H10C10.5523 13 11 13.4477 11 14V20C11 20.5523 10.5523 21 10 21H4C3.44772 21 3 20.5523 3 20V14Z"
			fill={color}
		/>
	</g>
</svg>
