<!-- ! This file is automatically generated, please don't edit it directly. -->

<svelte:options namespace="svg" />

<script lang="ts">
  export let size = 24
  export let color = 'currentColor'
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-tag-fill">
		<path
			class="oi-fill"
			fill-rule="evenodd"
			clip-rule="evenodd"
			d="M4.45544 12.4613C4.45544 13.0978 4.7083 13.7083 5.15839 14.1584L12.5603 21.5603C13.4976 22.4976 15.0172 22.4976 15.9545 21.5603L21.4712 16.0436C22.4085 15.1063 22.4085 13.5867 21.4712 12.6495L14.0693 5.2475C13.6192 4.79741 13.0087 4.54456 12.3722 4.54456H6.85544C5.52996 4.54456 4.45544 5.61907 4.45544 6.94456V12.4613ZM8.49379 6.98522C7.66536 6.98522 6.99379 7.65679 6.99379 8.48522C6.99379 9.31365 7.66536 9.98522 8.49379 9.98522H8.50579C9.33421 9.98522 10.0058 9.31365 10.0058 8.48522C10.0058 7.65679 9.33421 6.98522 8.50579 6.98522H8.49379Z"
			fill={color}
		/>
	</g>
</svg>
