<!-- ! This file is automatically generated, please don't edit it directly. -->

<svelte:options namespace="svg" />

<script lang="ts">
  export let size = 24
  export let color = 'currentColor'
  // svelte-ignore unused-export-let
  export let strokeWidth = 2
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-temperature-alt-2">
		<path
			class="oi-fill"
			fill-rule="evenodd"
			clip-rule="evenodd"
			d="M12 2C10.3431 2 9 3.34315 9 5H8.99997L9.00003 5.00729L9.05801 12.9569C7.81208 13.865 7 15.3371 7 17C7 19.7614 9.23858 22 12 22C14.7614 22 17 19.7614 17 17C17 15.3371 16.1879 13.865 14.942 12.9569L15 5.00729L15 5.00729V5C15 3.34315 13.6569 2 12 2ZM12.9781 8L13 4.99698C12.9984 4.44608 12.5513 4 12 4C11.4487 4 11.0016 4.44608 11 4.99698L11.0219 8H12.9781Z"
			fill={color}
		/>
		<path
			class="oi-line"
			d="M19 5H17"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-line"
			d="M19 8H17"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-line"
			d="M19 11H17"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
	</g>
</svg>
