<!-- ! This file is automatically generated, please don't edit it directly. -->

<svelte:options namespace="svg" />

<script lang="ts">
  export let size = 24
  export let color = 'currentColor'
  // svelte-ignore unused-export-let
  export let strokeWidth = 2
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-triangle-fill">
		<path
			class="oi-fill"
			fill-rule="evenodd"
			clip-rule="evenodd"
			d="M13.7432 4.05903C12.9786 2.69972 11.0215 2.69973 10.2569 4.05903L2.96679 17.0193C2.21686 18.3525 3.18029 19.9998 4.70994 19.9998H19.2902C20.8199 19.9998 21.7833 18.3525 21.0334 17.0193L13.7432 4.05903Z"
			fill={color}
		/>
	</g>
</svg>
