<!-- ! This file is automatically generated, please don't edit it directly. -->

<svelte:options namespace="svg" />

<script lang="ts">
  export let size = 24
  export let color = 'currentColor'
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-van-fill">
		<path
			class="oi-fill"
			d="M2 11C2 10.4477 2.44772 10 3 10H21C21.5523 10 22 10.4477 22 11V16C22 16.5523 21.5523 17 21 17H17.7324C17.9026 16.7058 18 16.3643 18 16C18 14.8954 17.1046 14 16 14C14.8954 14 14 14.8954 14 16C14 16.3643 14.0974 16.7058 14.2676 17H8.73244C8.90261 16.7058 9 16.3643 9 16C9 14.8954 8.10457 14 7 14C5.89543 14 5 14.8954 5 16C5 16.3643 5.09739 16.7058 5.26756 17H3C2.44772 17 2 16.5523 2 16V11Z"
			fill={color}
		/>
		<circle
			class="oi-ellipse"
			cx="7"
			cy="16"
			r="2"
			stroke={color}
			stroke-width={strokeWidth}
		/>
		<circle
			class="oi-ellipse"
			cx="16"
			cy="16"
			r="2"
			stroke={color}
			stroke-width={strokeWidth}
		/>
		<path
			class="oi-line"
			d="M8.5 11L8.5 6"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-line"
			d="M13.5 11L13.5 6"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M21 11L17.3002 6.3753C17.1105 6.13809 16.8232 6 16.5194 6H4C3.44772 6 3 6.44772 3 7V11H21Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-miterlimit="10"
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
	</g>
</svg>
