<!-- ! This file is automatically generated, please don't edit it directly. -->

<svelte:options namespace="svg" />

<script lang="ts">
  export let size = 24
  export let color = 'currentColor'
  // svelte-ignore unused-export-let
  export let strokeWidth = 2
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-volume-1">
		<path
			class="oi-vector"
			d="M10.9999 4.99994L5.9999 8.99994H1.9999V14.9999H5.9999L10.9999 18.9999V4.99994Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M19.0699 4.92999C20.9446 6.80527 21.9978 9.34835 21.9978 12C21.9978 14.6516 20.9446 17.1947 19.0699 19.07M15.5399 8.45999C16.4772 9.39763 17.0038 10.6692 17.0038 11.995C17.0038 13.3208 16.4772 14.5924 15.5399 15.53"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
	</g>
</svg>
