<!-- ! This file is automatically generated, please don't edit it directly. -->

<svelte:options namespace="svg" />

<script lang="ts">
  export let size = 24
  export let color = 'currentColor'
  // svelte-ignore unused-export-let
  export let strokeWidth = 2
</script>

<svg
	width={size}
	height={size}
	viewBox="0 0 24 24"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
	class="obra-icon"
>
	<g class="oi-watch">
		<path
			class="oi-ellipse"
			d="M12 18.3372C15.5 18.3372 18.3373 15.4999 18.3373 11.9999C18.3373 8.49991 15.5 5.6626 12 5.6626C8.50001 5.6626 5.66269 8.49991 5.66269 11.9999C5.66269 15.4999 8.50001 18.3372 12 18.3372Z"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M12 9.28406V12.0001L13.358 13.3581"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			class="oi-vector"
			d="M16.0831 16.8436L15.7662 20.311C15.7254 20.7624 15.5168 21.1822 15.1815 21.4872C14.8463 21.7923 14.4088 21.9605 13.9555 21.9587H10.0355C9.58219 21.9605 9.14471 21.7923 8.80946 21.4872C8.47421 21.1822 8.26559 20.7624 8.22479 20.311L7.90793 16.8436M7.91698 7.15652L8.23385 3.6891C8.2745 3.23922 8.48185 2.82078 8.81518 2.51593C9.1485 2.21107 9.58375 2.04182 10.0355 2.0414H13.9737C14.4269 2.03956 14.8644 2.2078 15.1997 2.51287C15.5349 2.81794 15.7435 3.23766 15.7843 3.6891L16.1012 7.15652"
			stroke={color}
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
	</g>
</svg>
