export const svgs = import.meta.glob('./svgs/*.svg', {
	as: 'raw',
	eager: true,
});

function cleanSvg(svg: string) {
	return svg
		.replace(
			// need the \! or better-comments goes crazy
			// prettier-ignore
			"<\!-- ! This file is automatically generated, please don't edit it directly. -->",
			'',
		)
		.replace(/stroke="black"/g, 'stroke="currentColor"')
		.replace(/fill="black"/g, 'fill="currentColor"')
		.trim();
}

export function getSvg(name: string) {
	return cleanSvg(svgs[`./svgs/${name}.svg`] || '');
}
