export const svgs = import.meta.glob('./svgs/*.svg', {
	as: 'raw',
	eager: true,
});

function prepareSvg(svg: string, strokeWeight: number) {
	return svg
		.replace(
			// need the \! or better-comments goes crazy
			// prettier-ignore
			"<\!-- ! This file is automatically generated, please don't edit it directly. -->",
			'',
		)
		.replace(/stroke="black"/g, 'stroke="currentColor"')
		.replace(/fill="black"/g, 'fill="currentColor"')
		.replace(/stroke-width="2"/g, `stroke-width="${strokeWeight}"`)
		.trim();
}

export function getSvg(name: string, strokeWeight: number) {
	return prepareSvg(svgs[`./svgs/${name}.svg`] || '', strokeWeight);
}
