//! This file is automatically generated, please don't edit it directly.

import type { FillIconProps } from '../types';
import React, { forwardRef } from 'react';

const BrandGoogleFill = forwardRef<SVGSVGElement, FillIconProps>(
	({ size = 24, color = 'currentColor', ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-brand-google-fill">
					<path
						className="oi-fill"
						d="M11.9575 5.95839C13.4325 5.95839 14.7533 6.46672 15.795 7.45839L18.6491 4.60422C16.9158 2.99173 14.6533 2.00006 11.9575 2.00006C8.04915 2.00006 4.66999 4.24172 3.02415 7.50839L6.34915 10.0875C7.13665 7.71672 9.34914 5.95839 11.9575 5.95839Z"
						fill={color}
					/>
					<path
						className="oi-fill"
						d="M21.5325 12.2294C21.5325 11.5753 21.47 10.942 21.3742 10.3336H11.9575V14.0919H17.3492C17.1075 15.3253 16.4075 16.3753 15.3575 17.0836L18.5783 19.5836C20.4575 17.8419 21.5325 15.2669 21.5325 12.2294Z"
						fill={color}
					/>
					<path
						className="oi-fill"
						d="M6.345 13.913C6.145 13.3088 6.02833 12.6672 6.02833 12.0005C6.02833 11.3338 6.14083 10.6922 6.345 10.088L3.02 7.50885C2.34084 8.85885 1.9575 10.3838 1.9575 12.0005C1.9575 13.6172 2.34084 15.1422 3.02417 16.4922L6.345 13.913Z"
						fill={color}
					/>
					<path
						className="oi-fill"
						d="M11.9575 22C14.6575 22 16.9283 21.1125 18.5783 19.5791L15.3575 17.0792C14.4617 17.6833 13.3075 18.0375 11.9575 18.0375C9.34916 18.0375 7.13666 16.2792 6.345 13.9083L3.02 16.4875C4.67 19.7583 8.04916 22 11.9575 22Z"
						fill={color}
					/>
				</g>
			</svg>
		);
	},
);

export default BrandGoogleFill;
