//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const Briefcase = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-briefcase">
					<path
						className="oi-box"
						d="M19.1999 7H4.79988C3.80577 7 2.99988 7.89543 2.99988 9V19C2.99988 20.1046 3.80577 21 4.79988 21H19.1999C20.194 21 20.9999 20.1046 20.9999 19V9C20.9999 7.89543 20.194 7 19.1999 7Z"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-vector"
						d="M15.9999 21V5C15.9999 4.46957 15.7892 3.96086 15.4141 3.58579C15.039 3.21071 14.5303 3 13.9999 3H9.99988C9.46944 3 8.96074 3.21071 8.58566 3.58579C8.21059 3.96086 7.99988 4.46957 7.99988 5V21"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
				</g>
			</svg>
		);
	},
);

export default Briefcase;
