//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const Bus = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-bus">
					<path
						className="oi-vector"
						d="M4 6H20V12H4V6Z"
						stroke={color}
						strokeWidth={strokeWidth}
						stroke-miterlimit="10"
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-vector"
						d="M4 12H20V17C20 18.1046 19.1046 19 18 19H6C4.89543 19 4 18.1046 4 17V12Z"
						stroke={color}
						strokeWidth={strokeWidth}
						stroke-miterlimit="10"
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-vector"
						d="M4 5C4 3.89543 4.89543 3 6 3H18C19.1046 3 20 3.89543 20 5V6H4V5Z"
						stroke={color}
						strokeWidth={strokeWidth}
						stroke-miterlimit="10"
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<rect
						className="oi-vector"
						x="5"
						y="19"
						width="1"
						height="2"
						stroke={color}
						strokeWidth={strokeWidth}
						stroke-miterlimit="10"
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<rect
						className="oi-vector"
						x="18"
						y="19"
						width="1"
						height="2"
						stroke={color}
						strokeWidth={strokeWidth}
						stroke-miterlimit="10"
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-medium-dot"
						d="M8 15.5H8.012"
						stroke={color}
						strokeWidth={strokeWidth * 1.5}
						strokeLinecap="round"
					/>
					<path
						className="oi-medium-dot"
						d="M16 15.5H16.012"
						stroke={color}
						strokeWidth={strokeWidth * 1.5}
						strokeLinecap="round"
					/>
				</g>
			</svg>
		);
	},
);

export default Bus;
