//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const Business = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-business">
					<rect
						className="oi-vector"
						x="5"
						y="3"
						width="14"
						height="18"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-line"
						d="M3.00002 21H21"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<rect
						className="oi-mini-square"
						x="9.63782"
						y="7.5"
						width="0.1"
						height="0.1"
						stroke={color}
						strokeWidth="1.5"
					/>
					<rect
						className="oi-mini-square"
						x="9.63782"
						y="12"
						width="0.1"
						height="0.1"
						stroke={color}
						strokeWidth="1.5"
					/>
					<rect
						className="oi-mini-square"
						x="9.63782"
						y="16.5"
						width="0.1"
						height="0.1"
						stroke={color}
						strokeWidth="1.5"
					/>
					<rect
						className="oi-mini-square"
						x="14.1495"
						y="16.5"
						width="0.1"
						height="0.1"
						stroke={color}
						strokeWidth="1.5"
					/>
					<rect
						className="oi-mini-square"
						x="14.1495"
						y="12.05"
						width="0.1"
						height="0.1"
						stroke={color}
						strokeWidth="1.5"
					/>
					<rect
						className="oi-mini-square"
						x="14.1495"
						y="7.55005"
						width="0.1"
						height="0.1"
						stroke={color}
						strokeWidth="1.5"
					/>
				</g>
			</svg>
		);
	},
);

export default Business;
