//! This file is automatically generated, please don't edit it directly.

import type { FillIconProps } from '../types';
import React, { forwardRef } from 'react';

const CalendarDatesFill = forwardRef<SVGSVGElement, FillIconProps>(
	({ size = 24, color = 'currentColor', ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-calendar-dates-fill">
					<path
						className="oi-fill"
						d="M8 6C8 6.55228 8.44772 7 9 7C9.55228 7 10 6.55228 10 6V3H14V6C14 6.55228 14.4477 7 15 7C15.5523 7 16 6.55228 16 6V3H19C20.6569 3 22 4.34315 22 6V19C22 20.6569 20.6569 22 19 22H5C3.34315 22 2 20.6569 2 19V6C2 4.34315 3.34315 3 5 3H8V6ZM6.5 18.5996H8.59961V16.5H6.5V18.5996ZM9.5 18.5996H11.5996V16.5H9.5V18.5996ZM12.5 18.5996H14.5996V16.5H12.5V18.5996ZM15.5 16.5V18.5996H17.5996V16.5H15.5ZM6.5 15.5996H8.59961V13.5H6.5V15.5996ZM9.5 15.5996H11.5996V13.5H9.5V15.5996ZM12.5 15.5996H14.5996V13.5H12.5V15.5996ZM15.5 15.5996H17.5996V13.5H15.5V15.5996ZM3 9C2.44772 9 2 9.44772 2 10C2 10.5523 2.44772 11 3 11H21C21.5523 11 22 10.5523 22 10C22 9.44772 21.5523 9 21 9H3Z"
						fill={color}
					/>
				</g>
			</svg>
		);
	},
);

export default CalendarDatesFill;
