//! This file is automatically generated, please don't edit it directly.

import type { FillIconProps } from '../types';
import React, { forwardRef } from 'react';

const CalendarFill = forwardRef<SVGSVGElement, FillIconProps>(
	({ size = 24, color = 'currentColor', ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-calendar-fill">
					<path
						className="oi-fill"
						d="M19 3C20.6569 3 22 4.34315 22 6V19C22 20.6569 20.6569 22 19 22H5C3.34315 22 2 20.6569 2 19V6C2 4.34315 3.34315 3 5 3H8V6C8 6.55228 8.44772 7 9 7C9.55228 7 10 6.55228 10 6V3H14V6C14 6.55228 14.4477 7 15 7C15.5523 7 16 6.55228 16 6V3H19ZM3 9C2.44772 9 2 9.44772 2 10C2 10.5523 2.44772 11 3 11H21C21.5523 11 22 10.5523 22 10C22 9.44772 21.5523 9 21 9H3Z"
						fill={color}
					/>
				</g>
			</svg>
		);
	},
);

export default CalendarFill;
