//! This file is automatically generated, please don't edit it directly.

import type { FillIconProps } from '../types';
import React, { forwardRef } from 'react';

const CameraFill = forwardRef<SVGSVGElement, FillIconProps>(
	({ size = 24, color = 'currentColor', ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-camera-fill">
					<path
						className="oi-fill"
						d="M14 3C14.296 3 14.5766 3.13139 14.7666 3.3584L16.5586 5.5H20C21.1046 5.5 22 6.39543 22 7.5V18C22 19.1046 21.1046 20 20 20H4C2.89543 20 2 19.1046 2 18V7.5C2 6.39543 2.89543 5.5 4 5.5H7.51953L9.21875 3.375C9.40852 3.13778 9.69622 3 10 3H14ZM12 8C9.79086 8 8 9.79086 8 12C8 14.2091 9.79086 16 12 16C14.2091 16 16 14.2091 16 12C16 9.79086 14.2091 8 12 8ZM12 10C13.1046 10 14 10.8954 14 12C14 13.1046 13.1046 14 12 14C10.8954 14 10 13.1046 10 12C10 10.8954 10.8954 10 12 10Z"
						fill={color}
					/>
				</g>
			</svg>
		);
	},
);

export default CameraFill;
