//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const CaretUp = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-caret-up">
					<path
						className="oi-vector"
						d="M8.06752 14C7.6436 14 7.41202 13.5056 7.68341 13.1799L11.6159 8.46093C11.8158 8.22105 12.1842 8.22106 12.3841 8.46093L16.3166 13.1799C16.588 13.5056 16.3564 14 15.9325 14L8.06752 14Z"
						stroke={color}
						strokeWidth={strokeWidth}
						stroke-miterlimit="10"
					/>
				</g>
			</svg>
		);
	},
);

export default CaretUp;
