//! This file is automatically generated, please don't edit it directly.

import type { FillIconProps } from '../types';
import React, { forwardRef } from 'react';

const CircleArrowLeftFill = forwardRef<SVGSVGElement, FillIconProps>(
	({ size = 24, color = 'currentColor', ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-circle-arrow-left-fill">
					<path
						className="oi-fill"
						d="M12 2C17.5228 2 22 6.47715 22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12C2 6.47715 6.47715 2 12 2ZM11.707 7.29297C11.3165 6.90244 10.6835 6.90244 10.293 7.29297L6.29297 11.293C5.90248 11.6835 5.90246 12.3165 6.29297 12.707L10.293 16.707C10.6835 17.0975 11.3165 17.0975 11.707 16.707C12.0975 16.3165 12.0975 15.6835 11.707 15.293L9.41406 13H17C17.5523 13 18 12.5522 18 12C18 11.4477 17.5523 11 17 11H9.41406L11.707 8.70703C12.0975 8.31652 12.0975 7.6835 11.707 7.29297Z"
						fill={color}
					/>
				</g>
			</svg>
		);
	},
);

export default CircleArrowLeftFill;
