//! This file is automatically generated, please don't edit it directly.

import type { FillIconProps } from '../types';
import React, { forwardRef } from 'react';

const CircleSubtractFill = forwardRef<SVGSVGElement, FillIconProps>(
	({ size = 24, color = 'currentColor', ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-circle-subtract-fill">
					<path
						className="oi-fill"
						d="M12.0002 1.80005C17.6335 1.80015 22.2004 6.367 22.2004 12.0002C22.2003 17.6334 17.6334 22.2003 12.0002 22.2004C6.367 22.2004 1.80015 17.6335 1.80005 12.0002C1.80005 6.36694 6.36694 1.80005 12.0002 1.80005ZM8.00024 11.0002C7.44796 11.0002 7.00024 11.448 7.00024 12.0002C7.00038 12.5524 7.44804 13.0002 8.00024 13.0002H16.0002C16.5523 13.0001 17.0001 12.5523 17.0002 12.0002C17.0002 11.448 16.5524 11.0004 16.0002 11.0002H8.00024Z"
						fill={color}
					/>
				</g>
			</svg>
		);
	},
);

export default CircleSubtractFill;
