//! This file is automatically generated, please don't edit it directly.

import type { FillIconProps } from '../types';
import React, { forwardRef } from 'react';

const CircleWarningFill = forwardRef<SVGSVGElement, FillIconProps>(
	({ size = 24, color = 'currentColor', ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-circle-warning-fill">
					<path
						className="oi-fill"
						d="M12 2C16.9706 2 22 7.02944 22 12C22 16.9706 16.9706 22 12 22C7.02944 22 2 16.9706 2 12C2 7.02944 7.02944 2 12 2ZM11.9971 15.7539C11.445 15.7541 10.9973 16.2019 10.9971 16.7539C10.9971 17.306 11.445 17.7538 11.9971 17.7539H12.0088C12.561 17.7539 13.0087 17.3061 13.0088 16.7539C13.0086 16.2018 12.561 15.7539 12.0088 15.7539H11.9971ZM12.0088 6.33008C11.4566 6.33023 11.0088 6.77789 11.0088 7.33008V13.3691C11.0088 13.4054 11.0109 13.4413 11.0146 13.4766C11.0485 13.9981 11.4817 14.411 12.0117 14.4111C12.5639 14.4111 13.0116 13.9633 13.0117 13.4111V7.37207C13.0117 7.33444 13.0089 7.29729 13.0049 7.26074C12.9692 6.74086 12.5377 6.33008 12.0088 6.33008Z"
						fill={color}
					/>
				</g>
			</svg>
		);
	},
);

export default CircleWarningFill;
