//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const CircleQuestion = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-circle-question">
					<circle
						className="oi-ellipse"
						cx="12"
						cy="12"
						r="9"
						stroke={color}
						strokeWidth={strokeWidth}
					/>
					<path
						className="oi-vector"
						d="M9.14319 9.81599C9.31526 8.94849 9.93419 7.5 12.1711 7.5C13.5026 7.5 14.8568 8.39777 14.8568 10.4282C14.8568 12.3177 13.3889 12.9323 12.3371 13.0898C12.0094 13.1389 11.7399 13.4048 11.7399 13.7362V14.0083"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
					/>
					<path
						className="oi-mini-dot"
						d="M11.7285 17H11.7405"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
					/>
				</g>
			</svg>
		);
	},
);

export default CircleQuestion;
