//! This file is automatically generated, please don't edit it directly.

import type { FillIconProps } from '../types';
import React, { forwardRef } from 'react';

const ClipboardErrorFill = forwardRef<SVGSVGElement, FillIconProps>(
	({ size = 24, color = 'currentColor', ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-clipboard-error-fill">
					<path
						className="oi-fill"
						d="M8.26953 2C8.09906 2.29437 8 2.63536 8 3V5C8 6.10457 8.89543 7 10 7H14C15.1046 7 16 6.10457 16 5V3C16 2.63536 15.9009 2.29437 15.7305 2H18C19.6569 2 21 3.34315 21 5V20C21 21.6569 19.6569 23 18 23H6C4.34315 23 3 21.6569 3 20V5C3 3.34315 4.34315 2 6 2H8.26953ZM14.707 10.793C14.3165 10.4024 13.6835 10.4024 13.293 10.793L12 12.0859L10.707 10.793C10.3165 10.4024 9.68349 10.4024 9.29297 10.793C8.90244 11.1835 8.90244 11.8165 9.29297 12.207L10.5859 13.5L9.29297 14.793C8.90244 15.1835 8.90244 15.8165 9.29297 16.207C9.6835 16.5975 10.3165 16.5975 10.707 16.207L12 14.9141L13.293 16.207C13.6835 16.5975 14.3165 16.5975 14.707 16.207C15.0975 15.8165 15.0975 15.1835 14.707 14.793L13.4141 13.5L14.707 12.207C15.0975 11.8165 15.0975 11.1835 14.707 10.793ZM14 5H10V3H14V5Z"
						fill={color}
					/>
				</g>
			</svg>
		);
	},
);

export default ClipboardErrorFill;
