//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const ClosedCaptioning = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-closed-captioning">
					<path
						className="oi-vector"
						d="M10.7396 10.4649C10.2872 9.9816 9.6459 9.67993 8.93464 9.67993C7.56464 9.67993 6.45404 10.7992 6.45404 12.1798C6.45404 13.5605 7.56464 14.6797 8.93464 14.6797C9.46998 14.6797 9.96571 14.5088 10.371 14.2182"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
					/>
					<path
						className="oi-box"
						d="M20 5H4C3.44772 5 3 5.44772 3 6V18C3 18.5523 3.44772 19 4 19H20C20.5523 19 21 18.5523 21 18V6C21 5.44772 20.5523 5 20 5Z"
						stroke={color}
						strokeWidth={strokeWidth}
						stroke-miterlimit="10"
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-vector"
						d="M17.546 10.4649C17.0936 9.9816 16.4523 9.67993 15.741 9.67993C14.371 9.67993 13.2604 10.7992 13.2604 12.1798C13.2604 13.5605 14.371 14.6797 15.741 14.6797C16.2764 14.6797 16.7721 14.5088 17.1774 14.2182"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
					/>
				</g>
			</svg>
		);
	},
);

export default ClosedCaptioning;
