//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const CoffeeBean = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-coffee-bean" clip-path="url(#clip0_944_30940)">
					<path
						className="oi-vector"
						d="M17.231 17.2311C21.2755 13.1866 22.2122 7.56584 19.3231 4.67682C16.4341 1.78779 10.8134 2.72448 6.76889 6.76897C2.7244 10.8135 1.78771 16.4342 4.67674 19.3232C7.56576 22.2122 13.1865 21.2755 17.231 17.2311Z"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-vector"
						d="M19.3228 4.67719C17.025 5.14594 13.0509 6.73969 12 12C10.9491 17.2603 6.975 18.8522 4.67719 19.3228"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
				</g>
				<defs>
					<clipPath className="clip0_944_30940">
						<rect width={size} height={size} fill="white" />
					</clipPath>
				</defs>
			</svg>
		);
	},
);

export default CoffeeBean;
