//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const ColdDrink = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-cold-drink">
					<path
						className="oi-vector"
						d="M5.625 7.5L7.5 21H17L18.5 7.5M5.625 7.5L5 3H19L18.5 7.5M5.625 7.5H18.5"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<rect
						className="oi-medium-square"
						x="10"
						y="11.3208"
						width="0.1"
						height="0.1"
						transform="rotate(-45 10 11.3208)"
						stroke={color}
						strokeWidth={strokeWidth}
					/>
					<rect
						className="oi-medium-square"
						x="13.5"
						y="13.5708"
						width="0.1"
						height="0.1"
						transform="rotate(-45 13.5 13.5708)"
						stroke={color}
						strokeWidth={strokeWidth}
					/>
					<rect
						className="oi-medium-square"
						x="11.5"
						y="16.8208"
						width="0.1"
						height="0.1"
						transform="rotate(-45 11.5 16.8208)"
						stroke={color}
						strokeWidth={strokeWidth}
					/>
				</g>
			</svg>
		);
	},
);

export default ColdDrink;
