//! This file is automatically generated, please don't edit it directly.

import type { FillIconProps } from '../types';
import React, { forwardRef } from 'react';

const CommentFill = forwardRef<SVGSVGElement, FillIconProps>(
	({ size = 24, color = 'currentColor', ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-comment-fill">
					<path
						className="oi-fill"
						d="M19 2C20.6569 2 22 3.34315 22 5V10L21.293 9.29297L9.29297 21.293L10 22H5C3.34315 22 2 20.6569 2 19V5C2 3.34315 3.34315 2 5 2H19ZM22 19C22 20.6569 20.6569 22 19 22H11.4141L22 11.4141V19Z"
						fill={color}
					/>
				</g>
			</svg>
		);
	},
);

export default CommentFill;
