//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const DiamondCards = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-diamond-cards">
					<path
						className="oi-vector"
						d="M11.4723 2.46864L2.46792 11.473C2.17686 11.764 2.17686 12.236 2.46792 12.527L11.4723 21.5314C11.7633 21.8224 12.2352 21.8224 12.5263 21.5314L21.5306 12.527C21.8217 12.236 21.8217 11.764 21.5306 11.473L12.5263 2.46864C12.2352 2.17758 11.7633 2.17758 11.4723 2.46864Z"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
				</g>
			</svg>
		);
	},
);

export default DiamondCards;
