//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const Divide = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-divide">
					<path
						className="oi-line"
						d="M20.4853 12.0001H3.51472"
						stroke={color}
						strokeWidth={strokeWidth}
						stroke-miterlimit="10"
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-dot"
						d="M11.9915 4.92053L12 4.92902"
						stroke={color}
						strokeWidth={strokeWidth * 2}
						strokeLinecap="round"
					/>
					<path
						className="oi-dot"
						d="M12 19.071L12.0085 19.0795"
						stroke={color}
						strokeWidth={strokeWidth * 2}
						strokeLinecap="round"
					/>
				</g>
			</svg>
		);
	},
);

export default Divide;
