//! This file is automatically generated, please don't edit it directly.

import type { FillIconProps } from '../types';
import React, { forwardRef } from 'react';

const DocumentUploadFill = forwardRef<SVGSVGElement, FillIconProps>(
	({ size = 24, color = 'currentColor', ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-document-upload-fill">
					<path
						className="oi-fill"
						d="M13 8C13 8.55228 13.4477 9 14 9H21V20C21 21.6569 19.6569 23 18 23H6C4.34315 23 3 21.6569 3 20V4C3 2.34315 4.34315 1 6 1H13V8ZM12.707 11.793C12.3409 11.4269 11.7619 11.4043 11.3691 11.7246L11.293 11.793L9.29297 13.793C8.90244 14.1835 8.90244 14.8165 9.29297 15.207C9.68349 15.5976 10.3165 15.5976 10.707 15.207L11 14.9141V17.5C11.0001 18.0522 11.4478 18.5 12 18.5C12.5522 18.5 12.9999 18.0522 13 17.5V14.9141L13.293 15.207C13.6835 15.5976 14.3165 15.5976 14.707 15.207C15.0976 14.8165 15.0976 14.1835 14.707 13.793L12.707 11.793ZM20.6973 6.83887C20.7478 6.88808 20.7924 6.94224 20.8311 7H15V1.30078L20.6973 6.83887Z"
						fill={color}
					/>
				</g>
			</svg>
		);
	},
);

export default DocumentUploadFill;
