//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const DocumentSmall = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-document-small">
					<path
						className="oi-box"
						d="M7.2 20.4H16.8C17.4627 20.4 18 19.8627 18 19.2V7.69703C18 7.37877 17.8736 7.07355 17.6485 6.8485L14.7515 3.95145C14.5264 3.7264 14.2212 3.59998 13.9029 3.59998H7.2C6.53726 3.59998 6 4.13723 6 4.79998V19.2C6 19.8627 6.53726 20.4 7.2 20.4Z"
						stroke={color}
						strokeWidth={strokeWidth}
					/>
					<path
						className="oi-vector"
						d="M14.4 13.2H9.59999"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
					/>
					<path
						className="oi-vector"
						d="M14.4 16.8H9.59999"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
					/>
				</g>
			</svg>
		);
	},
);

export default DocumentSmall;
