//! This file is automatically generated, please don't edit it directly.

import type { FillIconProps } from '../types';
import React, { forwardRef } from 'react';

const DocumentFill = forwardRef<SVGSVGElement, FillIconProps>(
	({ size = 24, color = 'currentColor', ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-document-fill">
					<path
						className="oi-fill"
						d="M14.3828 1.00488C14.6076 1.02681 14.8191 1.12448 14.9824 1.2832L20.6973 6.83887C20.8908 7.02713 21 7.28568 21 7.55566V20C21 21.6569 19.6569 23 18 23H6C4.34315 23 3 21.6569 3 20V4C3 2.34315 4.34315 1 6 1H14.2861L14.3828 1.00488ZM9 16C8.44772 16 8 16.4477 8 17C8 17.5523 8.44772 18 9 18H15C15.5523 18 16 17.5523 16 17C16 16.4477 15.5523 16 15 16H9ZM9 12C8.44772 12 8 12.4477 8 13C8 13.5523 8.44772 14 9 14H15C15.5523 14 16 13.5523 16 13C16 12.4477 15.5523 12 15 12H9ZM13 1C12.4477 1 12 1.44772 12 2V9C12 9.55228 12.4477 10 13 10H20C20.5523 10 21 9.55228 21 9C21 8.44772 20.5523 8 20 8H14V2C14 1.44772 13.5523 1 13 1Z"
						fill={color}
					/>
				</g>
			</svg>
		);
	},
);

export default DocumentFill;
