//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const Dress = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-dress" clip-path="url(#clip0_686_86303)">
					<path
						className="oi-line"
						d="M15 3.30188V0.75"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-line"
						d="M9 0.75V3.30188"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-vector"
						d="M18.75 21C18.8741 20.9999 18.9962 20.9691 19.1054 20.9103C19.2146 20.8514 19.3076 20.7664 19.3758 20.6628C19.4441 20.5592 19.4856 20.4403 19.4967 20.3167C19.5077 20.1931 19.4879 20.0687 19.4391 19.9547L15 10.5L17.1431 7.13625C17.2132 7.01961 17.2502 6.88609 17.2502 6.75C17.2502 6.61392 17.2132 6.4804 17.1431 6.36375L15 3.30188L14.3438 4.125C14.0627 4.47674 13.7061 4.76071 13.3004 4.95586C12.8947 5.15102 12.4502 5.25235 12 5.25235C11.5498 5.25235 11.1053 5.15102 10.6996 4.95586C10.2939 4.76071 9.93729 4.47674 9.65625 4.125L9 3.30282L6.85688 6.36375C6.78679 6.4804 6.74977 6.61392 6.74977 6.75C6.74977 6.88609 6.78679 7.01961 6.85688 7.13625L9 10.5L4.56188 19.9547C4.51306 20.0687 4.49325 20.193 4.50424 20.3165C4.51523 20.44 4.55667 20.5588 4.62484 20.6624C4.69302 20.766 4.78581 20.851 4.89491 20.9099C5.00401 20.9688 5.12601 20.9998 5.25 21H18.75Z"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-line"
						d="M9 10.5H15"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
				</g>
				<defs>
					<clipPath className="clip0_686_86303">
						<rect width={size} height={size} fill="white" />
					</clipPath>
				</defs>
			</svg>
		);
	},
);

export default Dress;
