//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const EmployeeBadge = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-employee-badge">
					<path
						className="oi-line"
						d="M14 12L18 12"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-line"
						d="M14 15.5L16.5 15.5"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<rect
						className="oi-box"
						x="7"
						y="11"
						width="3.5"
						height="5"
						rx="0.5"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
					/>
					<path
						className="oi-vector"
						d="M10.5 5.5H3.5C3.22386 5.5 3 5.72386 3 6V19C3 19.2761 3.22386 19.5 3.5 19.5H20.5C20.7761 19.5 21 19.2761 21 19V6C21 5.72386 20.7761 5.5 20.5 5.5H14"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
					/>
					<path
						className="oi-box"
						d="M13.5 3H11C10.7239 3 10.5 3.22386 10.5 3.5V7.5C10.5 7.77614 10.7239 8 11 8H13.5C13.7761 8 14 7.77614 14 7.5V3.5C14 3.22386 13.7761 3 13.5 3Z"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
					/>
				</g>
			</svg>
		);
	},
);

export default EmployeeBadge;
