//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const Eraser = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-eraser">
					<path
						className="oi-line"
						d="M8.5 20.913H19"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-vector"
						d="M14.8284 14.8284L19.7782 9.87867C20.5592 9.09763 20.5592 7.8313 19.7782 7.05025L16.9498 4.22182C16.1687 3.44077 14.9024 3.44077 14.1213 4.22182L9.17158 9.17157M14.8284 14.8284L9.87869 19.7782C9.09764 20.5592 7.83131 20.5592 7.05026 19.7782L4.22184 16.9497C3.44079 16.1687 3.44079 14.9024 4.22184 14.1213L9.17158 9.17157M14.8284 14.8284L9.17158 9.17157"
						stroke={color}
						strokeWidth={strokeWidth}
						stroke-miterlimit="10"
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
				</g>
			</svg>
		);
	},
);

export default Eraser;
