//! This file is automatically generated, please don't edit it directly.

import type { FillIconProps } from '../types';
import React, { forwardRef } from 'react';

const FolderAddFill = forwardRef<SVGSVGElement, FillIconProps>(
	({ size = 24, color = 'currentColor', ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-folder-add-fill">
					<path
						className="oi-fill"
						d="M9 4C9.26522 4 9.5195 4.10543 9.70703 4.29297L11.4141 6H20C21.1046 6 22 6.89543 22 8V18C22 19.1046 21.1046 20 20 20H4C2.89543 20 2 19.1046 2 18V6C2 4.89543 2.89543 4 4 4H9ZM12 9.5C11.4477 9.5 11 9.94772 11 10.5V12H9.5C8.94772 12 8.5 12.4477 8.5 13C8.5 13.5523 8.94772 14 9.5 14H11V15.5C11 16.0523 11.4477 16.5 12 16.5C12.5523 16.5 13 16.0523 13 15.5V14H14.5L14.6025 13.9951C15.1067 13.9438 15.5 13.5177 15.5 13C15.5 12.4823 15.1067 12.0562 14.6025 12.0049L14.5 12H13V10.5C13 9.94772 12.5523 9.5 12 9.5Z"
						fill={color}
					/>
				</g>
			</svg>
		);
	},
);

export default FolderAddFill;
