//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const Football = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-football">
					<path
						className="oi-vector"
						d="M17.4881 17.4881C13.4568 21.5194 7.86372 21.1959 5.17403 20.7403C4.69566 20.6595 4.25432 20.4317 3.91127 20.0887C3.56822 19.7456 3.34048 19.3043 3.25965 18.8259C2.80403 16.1362 2.48247 10.5412 6.51184 6.51187C10.5412 2.4825 16.1362 2.80406 18.8259 3.25968C19.3043 3.34051 19.7456 3.56826 20.0887 3.91131C20.4317 4.25436 20.6595 4.69569 20.7403 5.17406C21.1959 7.86375 21.5175 13.4587 17.4881 17.4881Z"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-line"
						d="M9.75 12L12 14.25"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-line"
						d="M12 9.75L14.25 12"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-line"
						d="M15 9L9 15"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-line"
						d="M13.6359 3.13593L20.8641 10.3641"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-line"
						d="M3.13593 13.6359L10.3641 20.8641"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
				</g>
			</svg>
		);
	},
);

export default Football;
