//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const GameControllerAlt = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-game-controller-alt">
					<path
						className="oi-line"
						d="M7 11.1666H10.3333"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-line"
						d="M8.66667 9.5V12.8333"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-mini-dot"
						d="M14.5 12H14.5083"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-mini-dot"
						d="M17 10.3334H17.0083"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-vector"
						d="M16.4333 6.16663H7.56667C6.7419 6.16682 5.94649 6.47277 5.33419 7.02535C4.7219 7.57792 4.3362 8.33787 4.25167 9.15829C4.24667 9.20163 4.24333 9.24246 4.2375 9.28496C4.17 9.84663 3.66667 14.0466 3.66667 15.3333C3.66667 15.9963 3.93006 16.6322 4.3989 17.1011C4.86774 17.5699 5.50362 17.8333 6.16667 17.8333C7 17.8333 7.41667 17.4166 7.83333 17L9.01167 15.8216C9.32415 15.509 9.74801 15.3334 10.19 15.3333H13.81C14.252 15.3334 14.6758 15.509 14.9883 15.8216L16.1667 17C16.5833 17.4166 17 17.8333 17.8333 17.8333C18.4964 17.8333 19.1323 17.5699 19.6011 17.1011C20.0699 16.6322 20.3333 15.9963 20.3333 15.3333C20.3333 14.0458 19.83 9.84663 19.7625 9.28496C19.7567 9.24329 19.7533 9.20163 19.7483 9.15913C19.664 8.33855 19.2784 7.5784 18.6661 7.02565C18.0537 6.47291 17.2582 6.16684 16.4333 6.16663Z"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
				</g>
			</svg>
		);
	},
);

export default GameControllerAlt;
