//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const Gas = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-gas">
					<path
						className="oi-vector"
						d="M16.25 15C16.25 17.2091 14.4591 19 12.25 19C10.0409 19 8.25 17.2091 8.25 15C8.25 12.7909 10.0409 9 12.25 9C14.4591 9 16.25 12.7909 16.25 15Z"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
					/>
					<path
						className="oi-vector"
						d="M19.5 14.31C19.5 18.4742 16.2541 21.85 12.25 21.85C8.24594 21.85 5 18.4742 5 14.31C5 10.1458 12.25 3 12.25 3C12.25 3 19.5 10.1458 19.5 14.31Z"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
					/>
				</g>
			</svg>
		);
	},
);

export default Gas;
