//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const HighDefinition = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-high-definition">
					<rect
						className="oi-box"
						x="3"
						y="5"
						width="18"
						height="14"
						rx="1"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-vector"
						d="M5.96863 9L5.96863 11.8618M5.96863 14.7236L5.96863 11.8618M10.4316 9V11.8618M10.4316 14.7236V11.8618M5.96863 11.8618H10.4316"
						stroke={color}
						strokeWidth={strokeWidth}
						stroke-miterlimit="2.16568"
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-vector"
						d="M13.2523 14.8039V9H15.2291C16.9561 9 18.0313 10.5974 18.0313 11.9031C18.0313 13.5352 17.0763 14.8039 15.2291 14.8039H13.2523Z"
						stroke={color}
						strokeWidth={strokeWidth}
						stroke-miterlimit="2.16568"
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
				</g>
			</svg>
		);
	},
);

export default HighDefinition;
