//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const Leaf = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-leaf">
					<path
						className="oi-vector"
						d="M15.4785 15.4786C17.3997 13.5574 17.1401 10.183 14.8988 7.94169C12 5.0429 5.04288 5.0429 5.04288 5.0429C5.04288 5.0429 5.04288 12 7.94168 14.8988C10.183 17.1401 13.5574 17.3997 15.4785 15.4786Z"
						stroke={color}
						strokeWidth={strokeWidth}
						stroke-miterlimit="10"
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-line"
						d="M19 19L11 11"
						stroke={color}
						strokeWidth={strokeWidth}
						stroke-miterlimit="2.16568"
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
				</g>
			</svg>
		);
	},
);

export default Leaf;
