//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const MarriageRing = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-marriage-ring">
					<circle
						className="oi-ellipse"
						cx="12"
						cy="14.5"
						r="6.5"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
					/>
					<path
						className="oi-vector"
						d="M12 8H12.9444L15.7371 3.77574C15.9569 3.44334 15.7185 3 15.3201 3H12M12 8H11.0556L8.26285 3.77574C8.0431 3.44334 8.28147 3 8.67994 3H12M12 8V3"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
					/>
				</g>
			</svg>
		);
	},
);

export default MarriageRing;
