//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const MasonryAlt = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-masonry-alt">
					<rect
						className="oi-box"
						x="21"
						y="3"
						width="7"
						height="9"
						rx="1"
						transform="rotate(90 21 3)"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<rect
						className="oi-box"
						x="12"
						y="14"
						width="7"
						height="9"
						rx="1"
						transform="rotate(90 12 14)"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<rect
						className="oi-box"
						x="8"
						y="3"
						width="7"
						height="5"
						rx="1"
						transform="rotate(90 8 3)"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<rect
						className="oi-box"
						x="21"
						y="14"
						width="7"
						height="5"
						rx="1"
						transform="rotate(90 21 14)"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
				</g>
			</svg>
		);
	},
);

export default MasonryAlt;
