//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const MessageAlt = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-message-alt">
					<path
						className="oi-vector"
						d="M20 5H4C3.44772 5 3 5.44772 3 6V17C3 17.5523 3.44772 18 4 18H9L12 21L15 18H20C20.5523 18 21 17.5523 21 17V6C21 5.44772 20.5523 5 20 5Z"
						stroke={color}
						strokeWidth={strokeWidth}
						stroke-miterlimit="10"
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-medium-dot"
						d="M16 11.5H16.012"
						stroke={color}
						strokeWidth={strokeWidth * 1.5}
						strokeLinecap="round"
					/>
					<path
						className="oi-medium-dot"
						d="M12 11.5H12.012"
						stroke={color}
						strokeWidth={strokeWidth * 1.5}
						strokeLinecap="round"
					/>
					<path
						className="oi-medium-dot"
						d="M8 11.5H8.012"
						stroke={color}
						strokeWidth={strokeWidth * 1.5}
						strokeLinecap="round"
					/>
				</g>
			</svg>
		);
	},
);

export default MessageAlt;
