//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const MessageCircle = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-message-circle">
					<path
						className="oi-vector"
						d="M12 19.3636C16.4183 19.3636 20 15.7005 20 11.1818C20 6.66312 16.4183 3 12 3C7.58172 3 4 6.66312 4 11.1818C4 13.0237 4.59511 14.7235 5.59941 16.0909L4 21L8.8 18.6828C9.77994 19.1207 10.8622 19.3636 12 19.3636Z"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
				</g>
			</svg>
		);
	},
);

export default MessageCircle;
