//! This file is automatically generated, please don't edit it directly.

import type { FillIconProps } from '../types';
import React, { forwardRef } from 'react';

const MessageFill = forwardRef<SVGSVGElement, FillIconProps>(
	({ size = 24, color = 'currentColor', ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-message-fill">
					<path
						className="oi-fill"
						d="M20 3C21.6569 3 23 4.34314 23 6V17C23 18.6569 21.6569 20 20 20H15.8281L13.4141 22.4141C12.633 23.1951 11.367 23.1951 10.5859 22.4141L8.17188 20H4C2.34315 20 1 18.6569 1 17V6C1 4.34315 2.34315 3 4 3H20ZM7 12.5C6.44772 12.5 6 12.9477 6 13.5C6 14.0523 6.44772 14.5 7 14.5H13L13.1025 14.4951C13.6067 14.4438 14 14.0177 14 13.5C14 12.9823 13.6067 12.5562 13.1025 12.5049L13 12.5H7ZM7 8.5C6.44772 8.5 6 8.94772 6 9.5C6 10.0523 6.44772 10.5 7 10.5H17C17.5523 10.5 18 10.0523 18 9.5C18 8.94772 17.5523 8.5 17 8.5H7Z"
						fill={color}
					/>
				</g>
			</svg>
		);
	},
);

export default MessageFill;
