//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const OptionsHorizontal = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-options-horizontal">
					<path
						className="oi-dot"
						d="M18.006 11.994L18.006 12.006"
						stroke={color}
						strokeWidth={strokeWidth * 2}
						strokeLinecap="round"
					/>
					<path
						className="oi-dot"
						d="M12.006 11.994L12.006 12.006"
						stroke={color}
						strokeWidth={strokeWidth * 2}
						strokeLinecap="round"
					/>
					<path
						className="oi-dot"
						d="M6.00598 11.994L6.00598 12.006"
						stroke={color}
						strokeWidth={strokeWidth * 2}
						strokeLinecap="round"
					/>
				</g>
			</svg>
		);
	},
);

export default OptionsHorizontal;
