//! This file is automatically generated, please don't edit it directly.

import type { FillIconProps } from '../types';
import React, { forwardRef } from 'react';

const PaintRollerFill = forwardRef<SVGSVGElement, FillIconProps>(
	({ size = 24, color = 'currentColor', ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-paint-roller-fill">
					<path
						className="oi-fill"
						d="M17 1C19.2091 1 21 2.79086 21 5V5.76758C21.6127 6.31685 22 7.11238 22 8V10C22 11.6569 20.6569 13 19 13H14C13.4823 13 13.0562 13.3933 13.0049 13.8975L13 14C14.1046 14 15 14.8954 15 16V20C15 21.1046 14.1046 22 13 22H11C9.89543 22 9 21.1046 9 20V16C9 14.8954 9.89543 14 11 14C11 12.3431 12.3431 11 14 11H7C4.79086 11 3 9.20914 3 7V5C3 2.79086 4.79086 1 7 1H17ZM19 11C19.5523 11 20 10.5523 20 10V9.64355C19.267 10.4747 18.1953 11 17 11H19Z"
						fill={color}
					/>
				</g>
			</svg>
		);
	},
);

export default PaintRollerFill;
