//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const PathCrossing = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-path-crossing">
					<path
						className="oi-line"
						d="M16.4667 4.8L13.1485 8.11815C12.6799 8.58678 11.9201 8.58678 11.4515 8.11815L8.13334 4.8"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
					/>
					<path
						className="oi-line"
						d="M16.4667 19.8L13.1485 16.4818C12.6799 16.0132 11.9201 16.0132 11.4515 16.4818L8.13334 19.8"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
					/>
					<path
						className="oi-line"
						d="M19.8 16.4667L16.4818 13.1485C16.0132 12.6799 16.0132 11.9201 16.4818 11.4515L19.8 8.13334"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
					/>
					<path
						className="oi-line"
						d="M4.8 16.4667L8.11814 13.1485C8.58677 12.6799 8.58677 11.9201 8.11814 11.4515L4.8 8.13334"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
					/>
				</g>
			</svg>
		);
	},
);

export default PathCrossing;
