//! This file is automatically generated, please don't edit it directly.

import type { FillIconProps } from '../types';
import React, { forwardRef } from 'react';

const PenAltFill = forwardRef<SVGSVGElement, FillIconProps>(
	({ size = 24, color = 'currentColor', ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-pen-alt-fill">
					<path
						className="oi-fill"
						d="M22.7074 13.8793C23.8785 15.0509 23.8787 16.95 22.7074 18.1215L18.1214 22.7074C16.95 23.8788 15.0508 23.8785 13.8792 22.7074L12.2933 21.1215L21.1214 12.2933L22.7074 13.8793ZM2.88315 1.47009C3.3944 1.22424 3.98502 1.12012 4.60287 1.20837L13.2894 2.44958C16.5092 2.90971 19.1304 5.27366 19.9193 8.42908L20.3675 10.224C20.3416 10.2452 20.3175 10.2691 20.2933 10.2933L10.2933 20.2933C10.2691 20.3175 10.2452 20.3416 10.224 20.3676L8.42905 19.9193C5.27363 19.1305 2.90969 16.5092 2.44955 13.2894L1.20834 4.60291C1.12009 3.98505 1.22421 3.39443 1.47006 2.88318L9.06967 10.4838C9.02569 10.6486 9.00034 10.8216 9.00034 11.0004C9.00052 12.1048 9.89588 13.0004 11.0003 13.0004H11.0121C12.1164 13.0002 13.0119 12.1047 13.0121 11.0004C13.0121 9.89591 12.1165 9.00055 11.0121 9.00037H11.0003C10.8216 9.00037 10.6486 9.02572 10.4837 9.0697L2.88315 1.47009Z"
						fill={color}
					/>
				</g>
			</svg>
		);
	},
);

export default PenAltFill;
