//! This file is automatically generated, please don't edit it directly.

import type { FillIconProps } from '../types';
import React, { forwardRef } from 'react';

const PencilFill = forwardRef<SVGSVGElement, FillIconProps>(
	({ size = 24, color = 'currentColor', ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-pencil-fill">
					<path
						className="oi-fill"
						d="M13.0137 5.15747C13.0456 5.35858 13.1379 5.55225 13.293 5.70728L18.293 10.7073C18.4478 10.862 18.641 10.9535 18.8418 10.9856L10.4141 19.4143C10.2227 19.6057 9.99444 19.7561 9.74316 19.8567L4.74316 21.8567C4.04682 22.1352 3.25738 21.9999 2.69531 21.5159L2.58594 21.4143C2.02021 20.8486 1.84642 19.9999 2.14355 19.2571L4.14355 14.2571C4.24413 14.0058 4.39455 13.7776 4.58594 13.5862L13.0137 5.15747ZM15.8789 2.29321C17.0505 1.12164 18.9495 1.12165 20.1211 2.29321L21.707 3.87915C22.8785 5.05073 22.8786 6.94981 21.707 8.12134L19.9854 9.84204C19.9533 9.64121 19.8618 9.44806 19.707 9.29321L14.707 4.29321C14.552 4.13814 14.3584 4.04583 14.1572 4.01392L15.8789 2.29321Z"
						fill={color}
					/>
				</g>
			</svg>
		);
	},
);

export default PencilFill;
