//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const Radio = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-radio">
					<circle
						className="oi-fill"
						cx="12"
						cy="12"
						r="3"
						fill={color}
					/>
					<circle
						className="oi-ellipse"
						cx="12"
						cy="12"
						r="6"
						stroke={color}
						strokeWidth={strokeWidth}
					/>
				</g>
			</svg>
		);
	},
);

export default Radio;
