//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const Rent = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-rent">
					<path
						className="oi-vector"
						d="M5 9.5V20C5 20.5523 5.44772 21 6 21H18C18.5523 21 19 20.5523 19 20V9.5"
						stroke={color}
						strokeWidth={strokeWidth}
						stroke-miterlimit="10"
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-incomplete-triangle"
						d="M3 11L12 3L21 11"
						stroke={color}
						strokeWidth={strokeWidth}
						stroke-miterlimit="10"
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-vector"
						d="M14.8749 11.4972C13.5189 10.025 9.6814 10.263 9.6814 14.1218C9.6814 17.9805 13.5794 17.839 14.8749 16.4326"
						stroke={color}
						strokeWidth="1.5"
						strokeLinecap="round"
					/>
					<path
						className="oi-line"
						d="M9.125 15.0229H12.8347"
						stroke={color}
						strokeWidth="1.5"
						strokeLinecap="round"
					/>
					<path
						className="oi-line"
						d="M9.125 13.0806H12.8347"
						stroke={color}
						strokeWidth="1.5"
						strokeLinecap="round"
					/>
				</g>
			</svg>
		);
	},
);

export default Rent;
