//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const RoadSignPointLeft = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-road-sign-point-left">
					<path
						className="oi-vector"
						d="M22 5V11H6L3 8L6 5H22Z"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinejoin="round"
					/>
					<path
						className="oi-vector"
						d="M13.5 11V22M13.5 2V5M16 22H11"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
				</g>
			</svg>
		);
	},
);

export default RoadSignPointLeft;
