//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const RoadSignBoth = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-road-sign-both">
					<path
						className="oi-vector"
						d="M5 4V8H19L21 6L19 4H5ZM19 11.5V15.5H5L3 13.5L5 11.5H19Z"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinejoin="round"
					/>
					<path
						className="oi-vector"
						d="M12 15.5V22M12 8V11.5M12 2V4M9.5 22H14.5"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
				</g>
			</svg>
		);
	},
);

export default RoadSignBoth;
