//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const Snow = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-snow">
					<path
						className="oi-vector"
						d="M19.0005 16C20.2147 15.0878 21 13.6356 21 12C21 9.23858 18.7614 7 16 7C15.9666 7 15.9334 7.00033 15.9002 7.00098C15.4373 4.71825 13.4193 3 11 3C8.23858 3 6 5.23858 6 8C6 8.37684 6.04169 8.74395 6.12071 9.09695C4.33457 9.4976 3 11.0929 3 13C3 14.1947 3.52375 15.2671 4.35418 16"
						stroke={color}
						strokeWidth={strokeWidth}
						stroke-miterlimit="10"
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-mini-dot"
						d="M9.5 17H9.512"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
					/>
					<path
						className="oi-mini-dot"
						d="M14.5004 16H14.5124"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
					/>
					<path
						className="oi-mini-dot"
						d="M13.5 20H13.512"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
					/>
					<path
						className="oi-mini-dot"
						d="M8.48804 21.0001H8.50004"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
					/>
				</g>
			</svg>
		);
	},
);

export default Snow;
