//! This file is automatically generated, please don't edit it directly.

import type { FillIconProps } from '../types';
import React, { forwardRef } from 'react';

const TagHorizontalFill = forwardRef<SVGSVGElement, FillIconProps>(
	({ size = 24, color = 'currentColor', ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-tag-horizontal-fill">
					<path
						className="oi-fill"
						d="M19.542 4C21.5423 4 23.2058 5.58891 23.2061 7.59961V15.4004C23.2058 17.4111 21.5423 19 19.542 19H8.65918C7.69522 19 6.76597 18.6265 6.07715 17.9541L2.08203 14.0537C0.639818 12.646 0.639817 10.354 2.08203 8.94629L6.07715 5.0459C6.76597 4.37355 7.69523 4 8.65918 4H19.542ZM7.03809 9.53125C6.20966 9.53125 5.53809 10.2028 5.53809 11.0312C5.53835 11.8595 6.20982 12.5312 7.03809 12.5312H7.0498C7.87807 12.5312 8.54954 11.8595 8.5498 11.0312C8.5498 10.2028 7.87823 9.53125 7.0498 9.53125H7.03809Z"
						fill={color}
					/>
				</g>
			</svg>
		);
	},
);

export default TagHorizontalFill;
