//! This file is automatically generated, please don't edit it directly.

import type { FillIconProps } from '../types';
import React, { forwardRef } from 'react';

const ThreeRowsFill = forwardRef<SVGSVGElement, FillIconProps>(
	({ size = 24, color = 'currentColor', ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-three-rows-fill">
					<rect
						className="oi-fill"
						x="3"
						y="3"
						width="18"
						height="5"
						rx="2"
						fill={color}
					/>
					<rect
						className="oi-fill"
						x="3"
						y="9.5"
						width="18"
						height="5"
						rx="2"
						fill={color}
					/>
					<rect
						className="oi-fill"
						x="3"
						y="16"
						width="18"
						height="5"
						rx="2"
						fill={color}
					/>
				</g>
			</svg>
		);
	},
);

export default ThreeRowsFill;
