//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const Tire = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-tire">
					<path
						className="oi-ellipse"
						d="M15.75 15.75C16.5784 15.75 17.25 14.0711 17.25 12C17.25 9.92893 16.5784 8.25 15.75 8.25C14.9216 8.25 14.25 9.92893 14.25 12C14.25 14.0711 14.9216 15.75 15.75 15.75Z"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-ellipse"
						d="M15.375 21C18.0674 21 20.25 16.9706 20.25 12C20.25 7.02944 18.0674 3 15.375 3C12.6826 3 10.5 7.02944 10.5 12C10.5 16.9706 12.6826 21 15.375 21Z"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-vector"
						d="M21.75 21H8.625C5.9325 21 3.75 16.9688 3.75 12C3.75 7.03125 5.9325 3 8.625 3H15.375"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-incomplete-triangle"
						d="M3.78561 10.9031L7.49999 8.25L10.5722 10.4447"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-incomplete-triangle"
						d="M4.39218 16.47L7.49999 14.25L11.3109 16.9716"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
				</g>
			</svg>
		);
	},
);

export default Tire;
