//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const TrademarkRegistered = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-trademark-registered">
					<path
						className="oi-ellipse"
						d="M12 21C16.9706 21 21 16.9706 21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21Z"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-vector"
						d="M9 16.0883V11.8544M9 11.8544V8.00012C9.78839 8.00012 12.2123 8.00012 12.9419 8.00012C14.303 8.00012 15 8.87009 15 9.9828C15 11.0068 13.9045 11.6337 13.0123 11.7858C12.7626 11.8283 12.1825 11.8668 11.9273 11.8544M9 11.8544H11.9273M11.9273 11.8544L14.4565 16.0883"
						stroke={color}
						strokeWidth={strokeWidth}
						stroke-miterlimit="2.16568"
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
				</g>
			</svg>
		);
	},
);

export default TrademarkRegistered;
