//! This file is automatically generated, please don't edit it directly.

import type { FillIconProps } from '../types';
import React, { forwardRef } from 'react';

const TriangleFill = forwardRef<SVGSVGElement, FillIconProps>(
	({ size = 24, color = 'currentColor', ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-triangle-fill">
					<path
						className="oi-fill"
						d="M9.38574 3.56885C10.5327 1.53 13.4683 1.52992 14.6152 3.56885L21.9053 16.5288C23.0302 18.5286 21.5845 20.9995 19.29 20.9995H4.70996C2.41548 20.9995 0.970812 18.5286 2.0957 16.5288L9.38574 3.56885Z"
						fill={color}
					/>
				</g>
			</svg>
		);
	},
);

export default TriangleFill;
