//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const Vegan = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-vegan">
					<path
						className="oi-vector"
						d="M19.6542 7.26579C20.7925 9.10615 21.2306 11.297 20.8846 13.4367C20.5301 15.6289 19.3776 17.6127 17.6488 19.0065C15.9199 20.4003 13.7368 21.1058 11.5193 20.9871C9.30173 20.8685 7.20633 19.9342 5.63604 18.364C4.06576 16.7937 3.13147 14.6983 3.01286 12.4807C2.89424 10.2632 3.59967 8.08008 4.99348 6.35124C6.3873 4.62241 8.37108 3.46993 10.5633 3.11543C12.6893 2.77165 14.8658 3.2019 16.6988 4.32402"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-vector"
						d="M3.00024 3C5.71706 5.16724 7.92943 7.89998 9.48367 11.0084C11.0379 14.1168 11.8967 17.5263 12.0005 21C12.8105 14.862 13.3505 12.45 15.6006 8.4"
						stroke={color}
						strokeWidth="1.80002"
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-vector"
						d="M15.5999 8.4C19.1999 8.4 21 6.6 21 3C17.3999 3 15.5999 4.8 15.5999 8.4Z"
						stroke={color}
						strokeWidth="1.80002"
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
				</g>
			</svg>
		);
	},
);

export default Vegan;
