//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const VideoCamera = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-video-camera">
					<path
						className="oi-vector"
						d="M20.4673 8.15137L15.079 12.0001L20.4673 15.8489V8.15137Z"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
					<path
						className="oi-vector"
						d="M13.5395 6.61169H5.07225C4.222 6.61169 3.53275 7.30095 3.53275 8.1512V15.8487C3.53275 16.699 4.222 17.3882 5.07225 17.3882H13.5395C14.3898 17.3882 15.079 16.699 15.079 15.8487V8.1512C15.079 7.30095 14.3898 6.61169 13.5395 6.61169Z"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
				</g>
			</svg>
		);
	},
);

export default VideoCamera;
