//! This file is automatically generated, please don't edit it directly.

import type { FillIconProps } from '../types';
import React, { forwardRef } from 'react';

const VolumeOffFill = forwardRef<SVGSVGElement, FillIconProps>(
	({ size = 24, color = 'currentColor', ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-volume-off-fill">
					<path
						className="oi-fill"
						d="M17.0215 19.8496C16.9927 19.8673 16.9645 19.8865 16.9336 19.9014C16.5871 20.0679 16.1752 20.0214 15.875 19.7812L11.1494 16H7.5C6.94772 16 6.5 15.5523 6.5 15V9.32812L17.0215 19.8496ZM15.875 4.21875C16.1752 3.97862 16.5871 3.93211 16.9336 4.09863C17.2799 4.26521 17.5 4.61571 17.5 5V14.6719L10.8281 8H11.1494L15.875 4.21875Z"
						fill={color}
					/>
					<path
						className="oi-fill"
						fill-rule="evenodd"
						clip-rule="evenodd"
						d="M4.29289 4.29289C4.68342 3.90237 5.31658 3.90237 5.70711 4.29289L19.7071 18.2929C20.0976 18.6834 20.0976 19.3166 19.7071 19.7071C19.3166 20.0976 18.6834 20.0976 18.2929 19.7071L4.29289 5.70711C3.90237 5.31658 3.90237 4.68342 4.29289 4.29289Z"
						fill={color}
					/>
				</g>
			</svg>
		);
	},
);

export default VolumeOffFill;
