//! This file is automatically generated, please don't edit it directly.

import type { StrokeIconProps } from '../types';
import React, { forwardRef } from 'react';

const Wheelchair = forwardRef<SVGSVGElement, StrokeIconProps>(
	({ size = 24, color = 'currentColor', strokeWidth = 2, ...props }, ref) => {
		return (
			<svg
				ref={ref}
				width={size}
				height={size}
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				{...props}
				className={`obra-icon ${props?.className || ''}`}
			>
				<g className="oi-wheelchair">
					<path
						className="oi-vector"
						d="M7.35347 11.1774C5.65262 12.1128 4.5 13.9218 4.5 16C4.5 19.0376 6.96243 21.5 10 21.5C11.6204 21.5 13.077 20.7993 14.0836 19.6844"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
					/>
					<path
						className="oi-vector"
						d="M11.5 7V11M19.5 20.5L15.6498 15.2059C15.5557 15.0765 15.4054 15 15.2454 15H12C11.7239 15 11.5 14.7761 11.5 14.5V11M11.5 11H16.5"
						stroke={color}
						strokeWidth={strokeWidth}
						strokeLinecap="round"
					/>
					<circle
						className="oi-ellipse"
						cx="11.5"
						cy="5"
						r="2"
						stroke={color}
						strokeWidth={strokeWidth}
					/>
				</g>
			</svg>
		);
	},
);

export default Wheelchair;
